// plugin-sdk/v1/proto/common.proto
//
// Shared types used by all Kleff plugin gRPC services.
// Source of truth for the wire contract. Generate Go code with:
//   protoc --go_out=. --go_opt=paths=source_relative \
//          --go-grpc_out=. --go-grpc_opt=paths=source_relative \
//          v1/proto/common.proto v1/proto/idp.proto
//
// The Go package ships hand-written gRPC stubs (codec.go, types.go,
// health.go, idp.go, middleware.go, routes.go, ui.go) that implement the
// same interface without requiring protoc at build time. Swap in generated
// code whenever you prefer.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: common.proto

package pluginsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginHealth_Health_FullMethodName          = "/kleff.plugins.v1.PluginHealth/Health"
	PluginHealth_GetCapabilities_FullMethodName = "/kleff.plugins.v1.PluginHealth/GetCapabilities"
)

// PluginHealthClient is the client API for PluginHealth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Every plugin must implement PluginHealth.
// The platform polls Health every 30 seconds and calls GetCapabilities once
// at registration time to discover which optional services the plugin exposes.
type PluginHealthClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// GetCapabilities declares which optional extension points this plugin
	// implements. Return an empty list (not an error) for no extra capabilities.
	GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error)
}

type pluginHealthClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginHealthClient(cc grpc.ClientConnInterface) PluginHealthClient {
	return &pluginHealthClient{cc}
}

func (c *pluginHealthClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, PluginHealth_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginHealthClient) GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCapabilitiesResponse)
	err := c.cc.Invoke(ctx, PluginHealth_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginHealthServer is the server API for PluginHealth service.
// All implementations must embed UnimplementedPluginHealthServer
// for forward compatibility.
//
// Every plugin must implement PluginHealth.
// The platform polls Health every 30 seconds and calls GetCapabilities once
// at registration time to discover which optional services the plugin exposes.
type PluginHealthServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// GetCapabilities declares which optional extension points this plugin
	// implements. Return an empty list (not an error) for no extra capabilities.
	GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error)
	mustEmbedUnimplementedPluginHealthServer()
}

// UnimplementedPluginHealthServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginHealthServer struct{}

func (UnimplementedPluginHealthServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedPluginHealthServer) GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedPluginHealthServer) mustEmbedUnimplementedPluginHealthServer() {}
func (UnimplementedPluginHealthServer) testEmbeddedByValue()                      {}

// UnsafePluginHealthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginHealthServer will
// result in compilation errors.
type UnsafePluginHealthServer interface {
	mustEmbedUnimplementedPluginHealthServer()
}

func RegisterPluginHealthServer(s grpc.ServiceRegistrar, srv PluginHealthServer) {
	// If the following call panics, it indicates UnimplementedPluginHealthServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginHealth_ServiceDesc, srv)
}

func _PluginHealth_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginHealthServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginHealth_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginHealthServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginHealth_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginHealthServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginHealth_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginHealthServer).GetCapabilities(ctx, req.(*GetCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginHealth_ServiceDesc is the grpc.ServiceDesc for PluginHealth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginHealth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kleff.plugins.v1.PluginHealth",
	HandlerType: (*PluginHealthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _PluginHealth_Health_Handler,
		},
		{
			MethodName: "GetCapabilities",
			Handler:    _PluginHealth_GetCapabilities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common.proto",
}
