// identity/framework.proto
//
// IdentityFramework — full IAM platform plugins (user CRUD, roles, groups,
// sessions). A framework plugin manages identity state; a provider plugin
// only validates tokens. Capability key: "identity.framework"

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: identity/framework.proto

package pluginsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_identity_framework_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_framework_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_identity_framework_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type CreateUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*CreateUserResponse_UserId
	//	*CreateUserResponse_Error
	Result        isCreateUserResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_identity_framework_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_framework_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_identity_framework_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserResponse) GetResult() isCreateUserResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CreateUserResponse) GetUserId() string {
	if x != nil {
		if x, ok := x.Result.(*CreateUserResponse_UserId); ok {
			return x.UserId
		}
	}
	return ""
}

func (x *CreateUserResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*CreateUserResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isCreateUserResponse_Result interface {
	isCreateUserResponse_Result()
}

type CreateUserResponse_UserId struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3,oneof"`
}

type CreateUserResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*CreateUserResponse_UserId) isCreateUserResponse_Result() {}

func (*CreateUserResponse_Error) isCreateUserResponse_Result() {}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_identity_framework_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_framework_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_identity_framework_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type UpdateUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*UpdateUserResponse_Ok
	//	*UpdateUserResponse_Error
	Result        isUpdateUserResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_identity_framework_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_framework_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_identity_framework_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserResponse) GetResult() isUpdateUserResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UpdateUserResponse) GetOk() bool {
	if x != nil {
		if x, ok := x.Result.(*UpdateUserResponse_Ok); ok {
			return x.Ok
		}
	}
	return false
}

func (x *UpdateUserResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*UpdateUserResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isUpdateUserResponse_Result interface {
	isUpdateUserResponse_Result()
}

type UpdateUserResponse_Ok struct {
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3,oneof"`
}

type UpdateUserResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*UpdateUserResponse_Ok) isUpdateUserResponse_Result() {}

func (*UpdateUserResponse_Error) isUpdateUserResponse_Result() {}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_identity_framework_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_framework_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_identity_framework_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*DeleteUserResponse_Ok
	//	*DeleteUserResponse_Error
	Result        isDeleteUserResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_identity_framework_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_framework_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_identity_framework_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteUserResponse) GetResult() isDeleteUserResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *DeleteUserResponse) GetOk() bool {
	if x != nil {
		if x, ok := x.Result.(*DeleteUserResponse_Ok); ok {
			return x.Ok
		}
	}
	return false
}

func (x *DeleteUserResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*DeleteUserResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isDeleteUserResponse_Result interface {
	isDeleteUserResponse_Result()
}

type DeleteUserResponse_Ok struct {
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3,oneof"`
}

type DeleteUserResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*DeleteUserResponse_Ok) isDeleteUserResponse_Result() {}

func (*DeleteUserResponse_Error) isDeleteUserResponse_Result() {}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_identity_framework_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_framework_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_identity_framework_proto_rawDescGZIP(), []int{6}
}

func (x *ListUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListUsersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ListUsersResponse_Users
	//	*ListUsersResponse_Error
	Result        isListUsersResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_identity_framework_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_framework_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_identity_framework_proto_rawDescGZIP(), []int{7}
}

func (x *ListUsersResponse) GetResult() isListUsersResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ListUsersResponse) GetUsers() *UserList {
	if x != nil {
		if x, ok := x.Result.(*ListUsersResponse_Users); ok {
			return x.Users
		}
	}
	return nil
}

func (x *ListUsersResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*ListUsersResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isListUsersResponse_Result interface {
	isListUsersResponse_Result()
}

type ListUsersResponse_Users struct {
	Users *UserList `protobuf:"bytes,1,opt,name=users,proto3,oneof"`
}

type ListUsersResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ListUsersResponse_Users) isListUsersResponse_Result() {}

func (*ListUsersResponse_Error) isListUsersResponse_Result() {}

type UserList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*UserEntry           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserList) Reset() {
	*x = UserList{}
	mi := &file_identity_framework_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserList) ProtoMessage() {}

func (x *UserList) ProtoReflect() protoreflect.Message {
	mi := &file_identity_framework_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserList.ProtoReflect.Descriptor instead.
func (*UserList) Descriptor() ([]byte, []int) {
	return file_identity_framework_proto_rawDescGZIP(), []int{8}
}

func (x *UserList) GetItems() []*UserEntry {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *UserList) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UserEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Roles         []string               `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserEntry) Reset() {
	*x = UserEntry{}
	mi := &file_identity_framework_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEntry) ProtoMessage() {}

func (x *UserEntry) ProtoReflect() protoreflect.Message {
	mi := &file_identity_framework_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEntry.ProtoReflect.Descriptor instead.
func (*UserEntry) Descriptor() ([]byte, []int) {
	return file_identity_framework_proto_rawDescGZIP(), []int{9}
}

func (x *UserEntry) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserEntry) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserEntry) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserEntry) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserEntry) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserEntry) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type SearchUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersRequest) Reset() {
	*x = SearchUsersRequest{}
	mi := &file_identity_framework_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersRequest) ProtoMessage() {}

func (x *SearchUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_framework_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersRequest.ProtoReflect.Descriptor instead.
func (*SearchUsersRequest) Descriptor() ([]byte, []int) {
	return file_identity_framework_proto_rawDescGZIP(), []int{10}
}

func (x *SearchUsersRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchUsersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchUsersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*SearchUsersResponse_Users
	//	*SearchUsersResponse_Error
	Result        isSearchUsersResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersResponse) Reset() {
	*x = SearchUsersResponse{}
	mi := &file_identity_framework_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersResponse) ProtoMessage() {}

func (x *SearchUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_framework_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersResponse.ProtoReflect.Descriptor instead.
func (*SearchUsersResponse) Descriptor() ([]byte, []int) {
	return file_identity_framework_proto_rawDescGZIP(), []int{11}
}

func (x *SearchUsersResponse) GetResult() isSearchUsersResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *SearchUsersResponse) GetUsers() *UserList {
	if x != nil {
		if x, ok := x.Result.(*SearchUsersResponse_Users); ok {
			return x.Users
		}
	}
	return nil
}

func (x *SearchUsersResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*SearchUsersResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isSearchUsersResponse_Result interface {
	isSearchUsersResponse_Result()
}

type SearchUsersResponse_Users struct {
	Users *UserList `protobuf:"bytes,1,opt,name=users,proto3,oneof"`
}

type SearchUsersResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*SearchUsersResponse_Users) isSearchUsersResponse_Result() {}

func (*SearchUsersResponse_Error) isSearchUsersResponse_Result() {}

type AssignRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleRequest) Reset() {
	*x = AssignRoleRequest{}
	mi := &file_identity_framework_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleRequest) ProtoMessage() {}

func (x *AssignRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_framework_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleRequest.ProtoReflect.Descriptor instead.
func (*AssignRoleRequest) Descriptor() ([]byte, []int) {
	return file_identity_framework_proto_rawDescGZIP(), []int{12}
}

func (x *AssignRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssignRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type AssignRoleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*AssignRoleResponse_Ok
	//	*AssignRoleResponse_Error
	Result        isAssignRoleResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleResponse) Reset() {
	*x = AssignRoleResponse{}
	mi := &file_identity_framework_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleResponse) ProtoMessage() {}

func (x *AssignRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_framework_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleResponse.ProtoReflect.Descriptor instead.
func (*AssignRoleResponse) Descriptor() ([]byte, []int) {
	return file_identity_framework_proto_rawDescGZIP(), []int{13}
}

func (x *AssignRoleResponse) GetResult() isAssignRoleResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *AssignRoleResponse) GetOk() bool {
	if x != nil {
		if x, ok := x.Result.(*AssignRoleResponse_Ok); ok {
			return x.Ok
		}
	}
	return false
}

func (x *AssignRoleResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*AssignRoleResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isAssignRoleResponse_Result interface {
	isAssignRoleResponse_Result()
}

type AssignRoleResponse_Ok struct {
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3,oneof"`
}

type AssignRoleResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*AssignRoleResponse_Ok) isAssignRoleResponse_Result() {}

func (*AssignRoleResponse_Error) isAssignRoleResponse_Result() {}

type RevokeRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRoleRequest) Reset() {
	*x = RevokeRoleRequest{}
	mi := &file_identity_framework_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRoleRequest) ProtoMessage() {}

func (x *RevokeRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_framework_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRoleRequest.ProtoReflect.Descriptor instead.
func (*RevokeRoleRequest) Descriptor() ([]byte, []int) {
	return file_identity_framework_proto_rawDescGZIP(), []int{14}
}

func (x *RevokeRoleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RevokeRoleRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type RevokeRoleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*RevokeRoleResponse_Ok
	//	*RevokeRoleResponse_Error
	Result        isRevokeRoleResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRoleResponse) Reset() {
	*x = RevokeRoleResponse{}
	mi := &file_identity_framework_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRoleResponse) ProtoMessage() {}

func (x *RevokeRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_framework_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRoleResponse.ProtoReflect.Descriptor instead.
func (*RevokeRoleResponse) Descriptor() ([]byte, []int) {
	return file_identity_framework_proto_rawDescGZIP(), []int{15}
}

func (x *RevokeRoleResponse) GetResult() isRevokeRoleResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RevokeRoleResponse) GetOk() bool {
	if x != nil {
		if x, ok := x.Result.(*RevokeRoleResponse_Ok); ok {
			return x.Ok
		}
	}
	return false
}

func (x *RevokeRoleResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*RevokeRoleResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isRevokeRoleResponse_Result interface {
	isRevokeRoleResponse_Result()
}

type RevokeRoleResponse_Ok struct {
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3,oneof"`
}

type RevokeRoleResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*RevokeRoleResponse_Ok) isRevokeRoleResponse_Result() {}

func (*RevokeRoleResponse_Error) isRevokeRoleResponse_Result() {}

type ListRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesRequest) Reset() {
	*x = ListRolesRequest{}
	mi := &file_identity_framework_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesRequest) ProtoMessage() {}

func (x *ListRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_framework_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesRequest.ProtoReflect.Descriptor instead.
func (*ListRolesRequest) Descriptor() ([]byte, []int) {
	return file_identity_framework_proto_rawDescGZIP(), []int{16}
}

type ListRolesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ListRolesResponse_Roles
	//	*ListRolesResponse_Error
	Result        isListRolesResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesResponse) Reset() {
	*x = ListRolesResponse{}
	mi := &file_identity_framework_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesResponse) ProtoMessage() {}

func (x *ListRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_framework_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesResponse.ProtoReflect.Descriptor instead.
func (*ListRolesResponse) Descriptor() ([]byte, []int) {
	return file_identity_framework_proto_rawDescGZIP(), []int{17}
}

func (x *ListRolesResponse) GetResult() isListRolesResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ListRolesResponse) GetRoles() *RoleList {
	if x != nil {
		if x, ok := x.Result.(*ListRolesResponse_Roles); ok {
			return x.Roles
		}
	}
	return nil
}

func (x *ListRolesResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*ListRolesResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isListRolesResponse_Result interface {
	isListRolesResponse_Result()
}

type ListRolesResponse_Roles struct {
	Roles *RoleList `protobuf:"bytes,1,opt,name=roles,proto3,oneof"`
}

type ListRolesResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ListRolesResponse_Roles) isListRolesResponse_Result() {}

func (*ListRolesResponse_Error) isListRolesResponse_Result() {}

type RoleList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []string               `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleList) Reset() {
	*x = RoleList{}
	mi := &file_identity_framework_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleList) ProtoMessage() {}

func (x *RoleList) ProtoReflect() protoreflect.Message {
	mi := &file_identity_framework_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleList.ProtoReflect.Descriptor instead.
func (*RoleList) Descriptor() ([]byte, []int) {
	return file_identity_framework_proto_rawDescGZIP(), []int{18}
}

func (x *RoleList) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type ListSessionsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CurrentSessionId string                 `protobuf:"bytes,2,opt,name=current_session_id,json=currentSessionId,proto3" json:"current_session_id,omitempty"` // hint for marking the active session
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_identity_framework_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_framework_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_identity_framework_proto_rawDescGZIP(), []int{19}
}

func (x *ListSessionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListSessionsRequest) GetCurrentSessionId() string {
	if x != nil {
		return x.CurrentSessionId
	}
	return ""
}

type ListSessionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ListSessionsResponse_Sessions
	//	*ListSessionsResponse_Error
	Result        isListSessionsResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_identity_framework_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_framework_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_identity_framework_proto_rawDescGZIP(), []int{20}
}

func (x *ListSessionsResponse) GetResult() isListSessionsResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ListSessionsResponse) GetSessions() *SessionList {
	if x != nil {
		if x, ok := x.Result.(*ListSessionsResponse_Sessions); ok {
			return x.Sessions
		}
	}
	return nil
}

func (x *ListSessionsResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*ListSessionsResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isListSessionsResponse_Result interface {
	isListSessionsResponse_Result()
}

type ListSessionsResponse_Sessions struct {
	Sessions *SessionList `protobuf:"bytes,1,opt,name=sessions,proto3,oneof"`
}

type ListSessionsResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ListSessionsResponse_Sessions) isListSessionsResponse_Result() {}

func (*ListSessionsResponse_Error) isListSessionsResponse_Result() {}

type SessionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Session             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionList) Reset() {
	*x = SessionList{}
	mi := &file_identity_framework_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionList) ProtoMessage() {}

func (x *SessionList) ProtoReflect() protoreflect.Message {
	mi := &file_identity_framework_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionList.ProtoReflect.Descriptor instead.
func (*SessionList) Descriptor() ([]byte, []int) {
	return file_identity_framework_proto_rawDescGZIP(), []int{21}
}

func (x *SessionList) GetItems() []*Session {
	if x != nil {
		return x.Items
	}
	return nil
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	LastAccess    int64                  `protobuf:"varint,7,opt,name=last_access,json=lastAccess,proto3" json:"last_access,omitempty"`
	Current       bool                   `protobuf:"varint,8,opt,name=current,proto3" json:"current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_identity_framework_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_identity_framework_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_identity_framework_proto_rawDescGZIP(), []int{22}
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Session) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Session) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *Session) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Session) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *Session) GetLastAccess() int64 {
	if x != nil {
		return x.LastAccess
	}
	return 0
}

func (x *Session) GetCurrent() bool {
	if x != nil {
		return x.Current
	}
	return false
}

type RevokeSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionRequest) Reset() {
	*x = RevokeSessionRequest{}
	mi := &file_identity_framework_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionRequest) ProtoMessage() {}

func (x *RevokeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_framework_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionRequest.ProtoReflect.Descriptor instead.
func (*RevokeSessionRequest) Descriptor() ([]byte, []int) {
	return file_identity_framework_proto_rawDescGZIP(), []int{23}
}

func (x *RevokeSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RevokeSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RevokeSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*RevokeSessionResponse_Ok
	//	*RevokeSessionResponse_Error
	Result        isRevokeSessionResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionResponse) Reset() {
	*x = RevokeSessionResponse{}
	mi := &file_identity_framework_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionResponse) ProtoMessage() {}

func (x *RevokeSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_framework_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionResponse.ProtoReflect.Descriptor instead.
func (*RevokeSessionResponse) Descriptor() ([]byte, []int) {
	return file_identity_framework_proto_rawDescGZIP(), []int{24}
}

func (x *RevokeSessionResponse) GetResult() isRevokeSessionResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RevokeSessionResponse) GetOk() bool {
	if x != nil {
		if x, ok := x.Result.(*RevokeSessionResponse_Ok); ok {
			return x.Ok
		}
	}
	return false
}

func (x *RevokeSessionResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*RevokeSessionResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isRevokeSessionResponse_Result interface {
	isRevokeSessionResponse_Result()
}

type RevokeSessionResponse_Ok struct {
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3,oneof"`
}

type RevokeSessionResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*RevokeSessionResponse_Ok) isRevokeSessionResponse_Result() {}

func (*RevokeSessionResponse_Error) isRevokeSessionResponse_Result() {}

type ChangePasswordRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CurrentPassword string                 `protobuf:"bytes,2,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	NewPassword     string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_identity_framework_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_framework_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_identity_framework_proto_rawDescGZIP(), []int{25}
}

func (x *ChangePasswordRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChangePasswordRequest) GetCurrentPassword() string {
	if x != nil {
		return x.CurrentPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ChangePasswordResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ChangePasswordResponse_Ok
	//	*ChangePasswordResponse_Error
	Result        isChangePasswordResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordResponse) Reset() {
	*x = ChangePasswordResponse{}
	mi := &file_identity_framework_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResponse) ProtoMessage() {}

func (x *ChangePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_framework_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResponse.ProtoReflect.Descriptor instead.
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return file_identity_framework_proto_rawDescGZIP(), []int{26}
}

func (x *ChangePasswordResponse) GetResult() isChangePasswordResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ChangePasswordResponse) GetOk() bool {
	if x != nil {
		if x, ok := x.Result.(*ChangePasswordResponse_Ok); ok {
			return x.Ok
		}
	}
	return false
}

func (x *ChangePasswordResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*ChangePasswordResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isChangePasswordResponse_Result interface {
	isChangePasswordResponse_Result()
}

type ChangePasswordResponse_Ok struct {
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3,oneof"`
}

type ChangePasswordResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ChangePasswordResponse_Ok) isChangePasswordResponse_Result() {}

func (*ChangePasswordResponse_Error) isChangePasswordResponse_Result() {}

type EnsureAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureAdminRequest) Reset() {
	*x = EnsureAdminRequest{}
	mi := &file_identity_framework_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureAdminRequest) ProtoMessage() {}

func (x *EnsureAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_framework_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureAdminRequest.ProtoReflect.Descriptor instead.
func (*EnsureAdminRequest) Descriptor() ([]byte, []int) {
	return file_identity_framework_proto_rawDescGZIP(), []int{27}
}

func (x *EnsureAdminRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *EnsureAdminRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EnsureAdminRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type EnsureAdminResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*EnsureAdminResponse_UserId
	//	*EnsureAdminResponse_Error
	Result        isEnsureAdminResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureAdminResponse) Reset() {
	*x = EnsureAdminResponse{}
	mi := &file_identity_framework_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureAdminResponse) ProtoMessage() {}

func (x *EnsureAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_framework_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureAdminResponse.ProtoReflect.Descriptor instead.
func (*EnsureAdminResponse) Descriptor() ([]byte, []int) {
	return file_identity_framework_proto_rawDescGZIP(), []int{28}
}

func (x *EnsureAdminResponse) GetResult() isEnsureAdminResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *EnsureAdminResponse) GetUserId() string {
	if x != nil {
		if x, ok := x.Result.(*EnsureAdminResponse_UserId); ok {
			return x.UserId
		}
	}
	return ""
}

func (x *EnsureAdminResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*EnsureAdminResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isEnsureAdminResponse_Result interface {
	isEnsureAdminResponse_Result()
}

type EnsureAdminResponse_UserId struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3,oneof"`
}

type EnsureAdminResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*EnsureAdminResponse_UserId) isEnsureAdminResponse_Result() {}

func (*EnsureAdminResponse_Error) isEnsureAdminResponse_Result() {}

var File_identity_framework_proto protoreflect.FileDescriptor

const file_identity_framework_proto_rawDesc = "" +
	"\n" +
	"\x18identity/framework.proto\x12\x10kleff.plugins.v1\x1a\fcommon.proto\"\x9d\x01\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\"j\n" +
	"\x12CreateUserResponse\x12\x19\n" +
	"\auser_id\x18\x01 \x01(\tH\x00R\x06userId\x12/\n" +
	"\x05error\x18\x02 \x01(\v2\x17.kleff.plugins.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"~\n" +
	"\x11UpdateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\"a\n" +
	"\x12UpdateUserResponse\x12\x10\n" +
	"\x02ok\x18\x01 \x01(\bH\x00R\x02ok\x12/\n" +
	"\x05error\x18\x02 \x01(\v2\x17.kleff.plugins.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\",\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"a\n" +
	"\x12DeleteUserResponse\x12\x10\n" +
	"\x02ok\x18\x01 \x01(\bH\x00R\x02ok\x12/\n" +
	"\x05error\x18\x02 \x01(\v2\x17.kleff.plugins.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"C\n" +
	"\x10ListUsersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x82\x01\n" +
	"\x11ListUsersResponse\x122\n" +
	"\x05users\x18\x01 \x01(\v2\x1a.kleff.plugins.v1.UserListH\x00R\x05users\x12/\n" +
	"\x05error\x18\x02 \x01(\v2\x17.kleff.plugins.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"S\n" +
	"\bUserList\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.kleff.plugins.v1.UserEntryR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xa8\x01\n" +
	"\tUserEntry\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12\x14\n" +
	"\x05roles\x18\x06 \x03(\tR\x05roles\"@\n" +
	"\x12SearchUsersRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x84\x01\n" +
	"\x13SearchUsersResponse\x122\n" +
	"\x05users\x18\x01 \x01(\v2\x1a.kleff.plugins.v1.UserListH\x00R\x05users\x12/\n" +
	"\x05error\x18\x02 \x01(\v2\x17.kleff.plugins.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"@\n" +
	"\x11AssignRoleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"a\n" +
	"\x12AssignRoleResponse\x12\x10\n" +
	"\x02ok\x18\x01 \x01(\bH\x00R\x02ok\x12/\n" +
	"\x05error\x18\x02 \x01(\v2\x17.kleff.plugins.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"@\n" +
	"\x11RevokeRoleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"a\n" +
	"\x12RevokeRoleResponse\x12\x10\n" +
	"\x02ok\x18\x01 \x01(\bH\x00R\x02ok\x12/\n" +
	"\x05error\x18\x02 \x01(\v2\x17.kleff.plugins.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"\x12\n" +
	"\x10ListRolesRequest\"\x82\x01\n" +
	"\x11ListRolesResponse\x122\n" +
	"\x05roles\x18\x01 \x01(\v2\x1a.kleff.plugins.v1.RoleListH\x00R\x05roles\x12/\n" +
	"\x05error\x18\x02 \x01(\v2\x17.kleff.plugins.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\" \n" +
	"\bRoleList\x12\x14\n" +
	"\x05roles\x18\x01 \x03(\tR\x05roles\"\\\n" +
	"\x13ListSessionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12,\n" +
	"\x12current_session_id\x18\x02 \x01(\tR\x10currentSessionId\"\x8e\x01\n" +
	"\x14ListSessionsResponse\x12;\n" +
	"\bsessions\x18\x01 \x01(\v2\x1d.kleff.plugins.v1.SessionListH\x00R\bsessions\x12/\n" +
	"\x05error\x18\x02 \x01(\v2\x17.kleff.plugins.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\">\n" +
	"\vSessionList\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.kleff.plugins.v1.SessionR\x05items\"\xe9\x01\n" +
	"\aSession\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tR\tuserAgent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x03R\texpiresAt\x12\x1f\n" +
	"\vlast_access\x18\a \x01(\x03R\n" +
	"lastAccess\x12\x18\n" +
	"\acurrent\x18\b \x01(\bR\acurrent\"N\n" +
	"\x14RevokeSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"d\n" +
	"\x15RevokeSessionResponse\x12\x10\n" +
	"\x02ok\x18\x01 \x01(\bH\x00R\x02ok\x12/\n" +
	"\x05error\x18\x02 \x01(\v2\x17.kleff.plugins.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"~\n" +
	"\x15ChangePasswordRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12)\n" +
	"\x10current_password\x18\x02 \x01(\tR\x0fcurrentPassword\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\"e\n" +
	"\x16ChangePasswordResponse\x12\x10\n" +
	"\x02ok\x18\x01 \x01(\bH\x00R\x02ok\x12/\n" +
	"\x05error\x18\x02 \x01(\v2\x17.kleff.plugins.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"b\n" +
	"\x12EnsureAdminRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"k\n" +
	"\x13EnsureAdminResponse\x12\x19\n" +
	"\auser_id\x18\x01 \x01(\tH\x00R\x06userId\x12/\n" +
	"\x05error\x18\x02 \x01(\v2\x17.kleff.plugins.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result2\xa7\t\n" +
	"\x11IdentityFramework\x12W\n" +
	"\n" +
	"CreateUser\x12#.kleff.plugins.v1.CreateUserRequest\x1a$.kleff.plugins.v1.CreateUserResponse\x12W\n" +
	"\n" +
	"UpdateUser\x12#.kleff.plugins.v1.UpdateUserRequest\x1a$.kleff.plugins.v1.UpdateUserResponse\x12W\n" +
	"\n" +
	"DeleteUser\x12#.kleff.plugins.v1.DeleteUserRequest\x1a$.kleff.plugins.v1.DeleteUserResponse\x12T\n" +
	"\tListUsers\x12\".kleff.plugins.v1.ListUsersRequest\x1a#.kleff.plugins.v1.ListUsersResponse\x12Z\n" +
	"\vSearchUsers\x12$.kleff.plugins.v1.SearchUsersRequest\x1a%.kleff.plugins.v1.SearchUsersResponse\x12W\n" +
	"\n" +
	"AssignRole\x12#.kleff.plugins.v1.AssignRoleRequest\x1a$.kleff.plugins.v1.AssignRoleResponse\x12W\n" +
	"\n" +
	"RevokeRole\x12#.kleff.plugins.v1.RevokeRoleRequest\x1a$.kleff.plugins.v1.RevokeRoleResponse\x12T\n" +
	"\tListRoles\x12\".kleff.plugins.v1.ListRolesRequest\x1a#.kleff.plugins.v1.ListRolesResponse\x12]\n" +
	"\fListSessions\x12%.kleff.plugins.v1.ListSessionsRequest\x1a&.kleff.plugins.v1.ListSessionsResponse\x12`\n" +
	"\rRevokeSession\x12&.kleff.plugins.v1.RevokeSessionRequest\x1a'.kleff.plugins.v1.RevokeSessionResponse\x12c\n" +
	"\x0eChangePassword\x12'.kleff.plugins.v1.ChangePasswordRequest\x1a(.kleff.plugins.v1.ChangePasswordResponse\x12Z\n" +
	"\vEnsureAdmin\x12$.kleff.plugins.v1.EnsureAdminRequest\x1a%.kleff.plugins.v1.EnsureAdminResponse\x12K\n" +
	"\x06Health\x12\x1f.kleff.plugins.v1.HealthRequest\x1a .kleff.plugins.v1.HealthResponseB/Z-github.com/kleffio/plugin-sdk-go/v1;pluginsv1b\x06proto3"

var (
	file_identity_framework_proto_rawDescOnce sync.Once
	file_identity_framework_proto_rawDescData []byte
)

func file_identity_framework_proto_rawDescGZIP() []byte {
	file_identity_framework_proto_rawDescOnce.Do(func() {
		file_identity_framework_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_framework_proto_rawDesc), len(file_identity_framework_proto_rawDesc)))
	})
	return file_identity_framework_proto_rawDescData
}

var file_identity_framework_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_identity_framework_proto_goTypes = []any{
	(*CreateUserRequest)(nil),      // 0: kleff.plugins.v1.CreateUserRequest
	(*CreateUserResponse)(nil),     // 1: kleff.plugins.v1.CreateUserResponse
	(*UpdateUserRequest)(nil),      // 2: kleff.plugins.v1.UpdateUserRequest
	(*UpdateUserResponse)(nil),     // 3: kleff.plugins.v1.UpdateUserResponse
	(*DeleteUserRequest)(nil),      // 4: kleff.plugins.v1.DeleteUserRequest
	(*DeleteUserResponse)(nil),     // 5: kleff.plugins.v1.DeleteUserResponse
	(*ListUsersRequest)(nil),       // 6: kleff.plugins.v1.ListUsersRequest
	(*ListUsersResponse)(nil),      // 7: kleff.plugins.v1.ListUsersResponse
	(*UserList)(nil),               // 8: kleff.plugins.v1.UserList
	(*UserEntry)(nil),              // 9: kleff.plugins.v1.UserEntry
	(*SearchUsersRequest)(nil),     // 10: kleff.plugins.v1.SearchUsersRequest
	(*SearchUsersResponse)(nil),    // 11: kleff.plugins.v1.SearchUsersResponse
	(*AssignRoleRequest)(nil),      // 12: kleff.plugins.v1.AssignRoleRequest
	(*AssignRoleResponse)(nil),     // 13: kleff.plugins.v1.AssignRoleResponse
	(*RevokeRoleRequest)(nil),      // 14: kleff.plugins.v1.RevokeRoleRequest
	(*RevokeRoleResponse)(nil),     // 15: kleff.plugins.v1.RevokeRoleResponse
	(*ListRolesRequest)(nil),       // 16: kleff.plugins.v1.ListRolesRequest
	(*ListRolesResponse)(nil),      // 17: kleff.plugins.v1.ListRolesResponse
	(*RoleList)(nil),               // 18: kleff.plugins.v1.RoleList
	(*ListSessionsRequest)(nil),    // 19: kleff.plugins.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),   // 20: kleff.plugins.v1.ListSessionsResponse
	(*SessionList)(nil),            // 21: kleff.plugins.v1.SessionList
	(*Session)(nil),                // 22: kleff.plugins.v1.Session
	(*RevokeSessionRequest)(nil),   // 23: kleff.plugins.v1.RevokeSessionRequest
	(*RevokeSessionResponse)(nil),  // 24: kleff.plugins.v1.RevokeSessionResponse
	(*ChangePasswordRequest)(nil),  // 25: kleff.plugins.v1.ChangePasswordRequest
	(*ChangePasswordResponse)(nil), // 26: kleff.plugins.v1.ChangePasswordResponse
	(*EnsureAdminRequest)(nil),     // 27: kleff.plugins.v1.EnsureAdminRequest
	(*EnsureAdminResponse)(nil),    // 28: kleff.plugins.v1.EnsureAdminResponse
	(*Error)(nil),                  // 29: kleff.plugins.v1.Error
	(*HealthRequest)(nil),          // 30: kleff.plugins.v1.HealthRequest
	(*HealthResponse)(nil),         // 31: kleff.plugins.v1.HealthResponse
}
var file_identity_framework_proto_depIdxs = []int32{
	29, // 0: kleff.plugins.v1.CreateUserResponse.error:type_name -> kleff.plugins.v1.Error
	29, // 1: kleff.plugins.v1.UpdateUserResponse.error:type_name -> kleff.plugins.v1.Error
	29, // 2: kleff.plugins.v1.DeleteUserResponse.error:type_name -> kleff.plugins.v1.Error
	8,  // 3: kleff.plugins.v1.ListUsersResponse.users:type_name -> kleff.plugins.v1.UserList
	29, // 4: kleff.plugins.v1.ListUsersResponse.error:type_name -> kleff.plugins.v1.Error
	9,  // 5: kleff.plugins.v1.UserList.items:type_name -> kleff.plugins.v1.UserEntry
	8,  // 6: kleff.plugins.v1.SearchUsersResponse.users:type_name -> kleff.plugins.v1.UserList
	29, // 7: kleff.plugins.v1.SearchUsersResponse.error:type_name -> kleff.plugins.v1.Error
	29, // 8: kleff.plugins.v1.AssignRoleResponse.error:type_name -> kleff.plugins.v1.Error
	29, // 9: kleff.plugins.v1.RevokeRoleResponse.error:type_name -> kleff.plugins.v1.Error
	18, // 10: kleff.plugins.v1.ListRolesResponse.roles:type_name -> kleff.plugins.v1.RoleList
	29, // 11: kleff.plugins.v1.ListRolesResponse.error:type_name -> kleff.plugins.v1.Error
	21, // 12: kleff.plugins.v1.ListSessionsResponse.sessions:type_name -> kleff.plugins.v1.SessionList
	29, // 13: kleff.plugins.v1.ListSessionsResponse.error:type_name -> kleff.plugins.v1.Error
	22, // 14: kleff.plugins.v1.SessionList.items:type_name -> kleff.plugins.v1.Session
	29, // 15: kleff.plugins.v1.RevokeSessionResponse.error:type_name -> kleff.plugins.v1.Error
	29, // 16: kleff.plugins.v1.ChangePasswordResponse.error:type_name -> kleff.plugins.v1.Error
	29, // 17: kleff.plugins.v1.EnsureAdminResponse.error:type_name -> kleff.plugins.v1.Error
	0,  // 18: kleff.plugins.v1.IdentityFramework.CreateUser:input_type -> kleff.plugins.v1.CreateUserRequest
	2,  // 19: kleff.plugins.v1.IdentityFramework.UpdateUser:input_type -> kleff.plugins.v1.UpdateUserRequest
	4,  // 20: kleff.plugins.v1.IdentityFramework.DeleteUser:input_type -> kleff.plugins.v1.DeleteUserRequest
	6,  // 21: kleff.plugins.v1.IdentityFramework.ListUsers:input_type -> kleff.plugins.v1.ListUsersRequest
	10, // 22: kleff.plugins.v1.IdentityFramework.SearchUsers:input_type -> kleff.plugins.v1.SearchUsersRequest
	12, // 23: kleff.plugins.v1.IdentityFramework.AssignRole:input_type -> kleff.plugins.v1.AssignRoleRequest
	14, // 24: kleff.plugins.v1.IdentityFramework.RevokeRole:input_type -> kleff.plugins.v1.RevokeRoleRequest
	16, // 25: kleff.plugins.v1.IdentityFramework.ListRoles:input_type -> kleff.plugins.v1.ListRolesRequest
	19, // 26: kleff.plugins.v1.IdentityFramework.ListSessions:input_type -> kleff.plugins.v1.ListSessionsRequest
	23, // 27: kleff.plugins.v1.IdentityFramework.RevokeSession:input_type -> kleff.plugins.v1.RevokeSessionRequest
	25, // 28: kleff.plugins.v1.IdentityFramework.ChangePassword:input_type -> kleff.plugins.v1.ChangePasswordRequest
	27, // 29: kleff.plugins.v1.IdentityFramework.EnsureAdmin:input_type -> kleff.plugins.v1.EnsureAdminRequest
	30, // 30: kleff.plugins.v1.IdentityFramework.Health:input_type -> kleff.plugins.v1.HealthRequest
	1,  // 31: kleff.plugins.v1.IdentityFramework.CreateUser:output_type -> kleff.plugins.v1.CreateUserResponse
	3,  // 32: kleff.plugins.v1.IdentityFramework.UpdateUser:output_type -> kleff.plugins.v1.UpdateUserResponse
	5,  // 33: kleff.plugins.v1.IdentityFramework.DeleteUser:output_type -> kleff.plugins.v1.DeleteUserResponse
	7,  // 34: kleff.plugins.v1.IdentityFramework.ListUsers:output_type -> kleff.plugins.v1.ListUsersResponse
	11, // 35: kleff.plugins.v1.IdentityFramework.SearchUsers:output_type -> kleff.plugins.v1.SearchUsersResponse
	13, // 36: kleff.plugins.v1.IdentityFramework.AssignRole:output_type -> kleff.plugins.v1.AssignRoleResponse
	15, // 37: kleff.plugins.v1.IdentityFramework.RevokeRole:output_type -> kleff.plugins.v1.RevokeRoleResponse
	17, // 38: kleff.plugins.v1.IdentityFramework.ListRoles:output_type -> kleff.plugins.v1.ListRolesResponse
	20, // 39: kleff.plugins.v1.IdentityFramework.ListSessions:output_type -> kleff.plugins.v1.ListSessionsResponse
	24, // 40: kleff.plugins.v1.IdentityFramework.RevokeSession:output_type -> kleff.plugins.v1.RevokeSessionResponse
	26, // 41: kleff.plugins.v1.IdentityFramework.ChangePassword:output_type -> kleff.plugins.v1.ChangePasswordResponse
	28, // 42: kleff.plugins.v1.IdentityFramework.EnsureAdmin:output_type -> kleff.plugins.v1.EnsureAdminResponse
	31, // 43: kleff.plugins.v1.IdentityFramework.Health:output_type -> kleff.plugins.v1.HealthResponse
	31, // [31:44] is the sub-list for method output_type
	18, // [18:31] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_identity_framework_proto_init() }
func file_identity_framework_proto_init() {
	if File_identity_framework_proto != nil {
		return
	}
	file_common_proto_init()
	file_identity_framework_proto_msgTypes[1].OneofWrappers = []any{
		(*CreateUserResponse_UserId)(nil),
		(*CreateUserResponse_Error)(nil),
	}
	file_identity_framework_proto_msgTypes[3].OneofWrappers = []any{
		(*UpdateUserResponse_Ok)(nil),
		(*UpdateUserResponse_Error)(nil),
	}
	file_identity_framework_proto_msgTypes[5].OneofWrappers = []any{
		(*DeleteUserResponse_Ok)(nil),
		(*DeleteUserResponse_Error)(nil),
	}
	file_identity_framework_proto_msgTypes[7].OneofWrappers = []any{
		(*ListUsersResponse_Users)(nil),
		(*ListUsersResponse_Error)(nil),
	}
	file_identity_framework_proto_msgTypes[11].OneofWrappers = []any{
		(*SearchUsersResponse_Users)(nil),
		(*SearchUsersResponse_Error)(nil),
	}
	file_identity_framework_proto_msgTypes[13].OneofWrappers = []any{
		(*AssignRoleResponse_Ok)(nil),
		(*AssignRoleResponse_Error)(nil),
	}
	file_identity_framework_proto_msgTypes[15].OneofWrappers = []any{
		(*RevokeRoleResponse_Ok)(nil),
		(*RevokeRoleResponse_Error)(nil),
	}
	file_identity_framework_proto_msgTypes[17].OneofWrappers = []any{
		(*ListRolesResponse_Roles)(nil),
		(*ListRolesResponse_Error)(nil),
	}
	file_identity_framework_proto_msgTypes[20].OneofWrappers = []any{
		(*ListSessionsResponse_Sessions)(nil),
		(*ListSessionsResponse_Error)(nil),
	}
	file_identity_framework_proto_msgTypes[24].OneofWrappers = []any{
		(*RevokeSessionResponse_Ok)(nil),
		(*RevokeSessionResponse_Error)(nil),
	}
	file_identity_framework_proto_msgTypes[26].OneofWrappers = []any{
		(*ChangePasswordResponse_Ok)(nil),
		(*ChangePasswordResponse_Error)(nil),
	}
	file_identity_framework_proto_msgTypes[28].OneofWrappers = []any{
		(*EnsureAdminResponse_UserId)(nil),
		(*EnsureAdminResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_framework_proto_rawDesc), len(file_identity_framework_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_identity_framework_proto_goTypes,
		DependencyIndexes: file_identity_framework_proto_depIdxs,
		MessageInfos:      file_identity_framework_proto_msgTypes,
	}.Build()
	File_identity_framework_proto = out.File
	file_identity_framework_proto_goTypes = nil
	file_identity_framework_proto_depIdxs = nil
}
