// identity/provider.proto
//
// IdentityProvider — AuthN plugins (Keycloak, Authentik, etc.)
// Handles login, token validation, and OIDC config.
// Capability key: "identity.provider"

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: identity/provider.proto

package pluginsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_identity_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_identity_provider_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TokenClaims struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Roles         []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenClaims) Reset() {
	*x = TokenClaims{}
	mi := &file_identity_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenClaims) ProtoMessage() {}

func (x *TokenClaims) ProtoReflect() protoreflect.Message {
	mi := &file_identity_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenClaims.ProtoReflect.Descriptor instead.
func (*TokenClaims) Descriptor() ([]byte, []int) {
	return file_identity_provider_proto_rawDescGZIP(), []int{1}
}

func (x *TokenClaims) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *TokenClaims) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TokenClaims) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *TokenClaims) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ValidateTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ValidateTokenResponse_Claims
	//	*ValidateTokenResponse_Error
	Result        isValidateTokenResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_identity_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_identity_provider_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateTokenResponse) GetResult() isValidateTokenResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ValidateTokenResponse) GetClaims() *TokenClaims {
	if x != nil {
		if x, ok := x.Result.(*ValidateTokenResponse_Claims); ok {
			return x.Claims
		}
	}
	return nil
}

func (x *ValidateTokenResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*ValidateTokenResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isValidateTokenResponse_Result interface {
	isValidateTokenResponse_Result()
}

type ValidateTokenResponse_Claims struct {
	Claims *TokenClaims `protobuf:"bytes,1,opt,name=claims,proto3,oneof"`
}

type ValidateTokenResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ValidateTokenResponse_Claims) isValidateTokenResponse_Result() {}

func (*ValidateTokenResponse_Error) isValidateTokenResponse_Result() {}

type GetOIDCConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOIDCConfigRequest) Reset() {
	*x = GetOIDCConfigRequest{}
	mi := &file_identity_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOIDCConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOIDCConfigRequest) ProtoMessage() {}

func (x *GetOIDCConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOIDCConfigRequest.ProtoReflect.Descriptor instead.
func (*GetOIDCConfigRequest) Descriptor() ([]byte, []int) {
	return file_identity_provider_proto_rawDescGZIP(), []int{3}
}

type OIDCConfig struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Authority             string                 `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	ClientId              string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	JwksUri               string                 `protobuf:"bytes,3,opt,name=jwks_uri,json=jwksUri,proto3" json:"jwks_uri,omitempty"`
	Scopes                []string               `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"`
	AuthMode              string                 `protobuf:"bytes,5,opt,name=auth_mode,json=authMode,proto3" json:"auth_mode,omitempty"` // "headless" or "redirect"
	TokenEndpoint         string                 `protobuf:"bytes,6,opt,name=token_endpoint,json=tokenEndpoint,proto3" json:"token_endpoint,omitempty"`
	AuthorizationEndpoint string                 `protobuf:"bytes,7,opt,name=authorization_endpoint,json=authorizationEndpoint,proto3" json:"authorization_endpoint,omitempty"`
	UserinfoEndpoint      string                 `protobuf:"bytes,8,opt,name=userinfo_endpoint,json=userinfoEndpoint,proto3" json:"userinfo_endpoint,omitempty"`
	EndSessionEndpoint    string                 `protobuf:"bytes,9,opt,name=end_session_endpoint,json=endSessionEndpoint,proto3" json:"end_session_endpoint,omitempty"`
	InternalTokenEndpoint string                 `protobuf:"bytes,10,opt,name=internal_token_endpoint,json=internalTokenEndpoint,proto3" json:"internal_token_endpoint,omitempty"` // Docker-internal URL for server-side PKCE proxy
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *OIDCConfig) Reset() {
	*x = OIDCConfig{}
	mi := &file_identity_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OIDCConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OIDCConfig) ProtoMessage() {}

func (x *OIDCConfig) ProtoReflect() protoreflect.Message {
	mi := &file_identity_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OIDCConfig.ProtoReflect.Descriptor instead.
func (*OIDCConfig) Descriptor() ([]byte, []int) {
	return file_identity_provider_proto_rawDescGZIP(), []int{4}
}

func (x *OIDCConfig) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *OIDCConfig) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *OIDCConfig) GetJwksUri() string {
	if x != nil {
		return x.JwksUri
	}
	return ""
}

func (x *OIDCConfig) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *OIDCConfig) GetAuthMode() string {
	if x != nil {
		return x.AuthMode
	}
	return ""
}

func (x *OIDCConfig) GetTokenEndpoint() string {
	if x != nil {
		return x.TokenEndpoint
	}
	return ""
}

func (x *OIDCConfig) GetAuthorizationEndpoint() string {
	if x != nil {
		return x.AuthorizationEndpoint
	}
	return ""
}

func (x *OIDCConfig) GetUserinfoEndpoint() string {
	if x != nil {
		return x.UserinfoEndpoint
	}
	return ""
}

func (x *OIDCConfig) GetEndSessionEndpoint() string {
	if x != nil {
		return x.EndSessionEndpoint
	}
	return ""
}

func (x *OIDCConfig) GetInternalTokenEndpoint() string {
	if x != nil {
		return x.InternalTokenEndpoint
	}
	return ""
}

type GetOIDCConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetOIDCConfigResponse_Config
	//	*GetOIDCConfigResponse_Error
	Result        isGetOIDCConfigResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOIDCConfigResponse) Reset() {
	*x = GetOIDCConfigResponse{}
	mi := &file_identity_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOIDCConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOIDCConfigResponse) ProtoMessage() {}

func (x *GetOIDCConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOIDCConfigResponse.ProtoReflect.Descriptor instead.
func (*GetOIDCConfigResponse) Descriptor() ([]byte, []int) {
	return file_identity_provider_proto_rawDescGZIP(), []int{5}
}

func (x *GetOIDCConfigResponse) GetResult() isGetOIDCConfigResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetOIDCConfigResponse) GetConfig() *OIDCConfig {
	if x != nil {
		if x, ok := x.Result.(*GetOIDCConfigResponse_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *GetOIDCConfigResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*GetOIDCConfigResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGetOIDCConfigResponse_Result interface {
	isGetOIDCConfigResponse_Result()
}

type GetOIDCConfigResponse_Config struct {
	Config *OIDCConfig `protobuf:"bytes,1,opt,name=config,proto3,oneof"`
}

type GetOIDCConfigResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetOIDCConfigResponse_Config) isGetOIDCConfigResponse_Result() {}

func (*GetOIDCConfigResponse_Error) isGetOIDCConfigResponse_Result() {}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_identity_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_identity_provider_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*RefreshTokenResponse_Token
	//	*RefreshTokenResponse_Error
	Result        isRefreshTokenResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_identity_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_identity_provider_proto_rawDescGZIP(), []int{7}
}

func (x *RefreshTokenResponse) GetResult() isRefreshTokenResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RefreshTokenResponse) GetToken() *TokenSet {
	if x != nil {
		if x, ok := x.Result.(*RefreshTokenResponse_Token); ok {
			return x.Token
		}
	}
	return nil
}

func (x *RefreshTokenResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*RefreshTokenResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isRefreshTokenResponse_Result interface {
	isRefreshTokenResponse_Result()
}

type RefreshTokenResponse_Token struct {
	Token *TokenSet `protobuf:"bytes,1,opt,name=token,proto3,oneof"`
}

type RefreshTokenResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*RefreshTokenResponse_Token) isRefreshTokenResponse_Result() {}

func (*RefreshTokenResponse_Error) isRefreshTokenResponse_Result() {}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_identity_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_identity_provider_proto_rawDescGZIP(), []int{8}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*LoginResponse_Token
	//	*LoginResponse_Error
	Result        isLoginResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_identity_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_identity_provider_proto_rawDescGZIP(), []int{9}
}

func (x *LoginResponse) GetResult() isLoginResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *LoginResponse) GetToken() *TokenSet {
	if x != nil {
		if x, ok := x.Result.(*LoginResponse_Token); ok {
			return x.Token
		}
	}
	return nil
}

func (x *LoginResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*LoginResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isLoginResponse_Result interface {
	isLoginResponse_Result()
}

type LoginResponse_Token struct {
	Token *TokenSet `protobuf:"bytes,1,opt,name=token,proto3,oneof"`
}

type LoginResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*LoginResponse_Token) isLoginResponse_Result() {}

func (*LoginResponse_Error) isLoginResponse_Result() {}

type TokenSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	IdToken       string                 `protobuf:"bytes,3,opt,name=id_token,json=idToken,proto3" json:"id_token,omitempty"`
	TokenType     string                 `protobuf:"bytes,4,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,5,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	Scope         string                 `protobuf:"bytes,6,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenSet) Reset() {
	*x = TokenSet{}
	mi := &file_identity_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenSet) ProtoMessage() {}

func (x *TokenSet) ProtoReflect() protoreflect.Message {
	mi := &file_identity_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenSet.ProtoReflect.Descriptor instead.
func (*TokenSet) Descriptor() ([]byte, []int) {
	return file_identity_provider_proto_rawDescGZIP(), []int{10}
}

func (x *TokenSet) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenSet) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TokenSet) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

func (x *TokenSet) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *TokenSet) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *TokenSet) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_identity_provider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_provider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_identity_provider_proto_rawDescGZIP(), []int{11}
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RegisterRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*RegisterResponse_UserId
	//	*RegisterResponse_Error
	Result        isRegisterResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_identity_provider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_provider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_identity_provider_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterResponse) GetResult() isRegisterResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil {
		if x, ok := x.Result.(*RegisterResponse_UserId); ok {
			return x.UserId
		}
	}
	return ""
}

func (x *RegisterResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*RegisterResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isRegisterResponse_Result interface {
	isRegisterResponse_Result()
}

type RegisterResponse_UserId struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3,oneof"`
}

type RegisterResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*RegisterResponse_UserId) isRegisterResponse_Result() {}

func (*RegisterResponse_Error) isRegisterResponse_Result() {}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_identity_provider_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_provider_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_identity_provider_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetUserResponse_User
	//	*GetUserResponse_Error
	Result        isGetUserResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_identity_provider_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_provider_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_identity_provider_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserResponse) GetResult() isGetUserResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetUserResponse) GetUser() *UserInfo {
	if x != nil {
		if x, ok := x.Result.(*GetUserResponse_User); ok {
			return x.User
		}
	}
	return nil
}

func (x *GetUserResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*GetUserResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGetUserResponse_Result interface {
	isGetUserResponse_Result()
}

type GetUserResponse_User struct {
	User *UserInfo `protobuf:"bytes,1,opt,name=user,proto3,oneof"`
}

type GetUserResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetUserResponse_User) isGetUserResponse_Result() {}

func (*GetUserResponse_Error) isGetUserResponse_Result() {}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_identity_provider_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_identity_provider_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_identity_provider_proto_rawDescGZIP(), []int{15}
}

func (x *UserInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserInfo) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

var File_identity_provider_proto protoreflect.FileDescriptor

const file_identity_provider_proto_rawDesc = "" +
	"\n" +
	"\x17identity/provider.proto\x12\x10kleff.plugins.v1\x1a\fcommon.proto\",\n" +
	"\x14ValidateTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"o\n" +
	"\vTokenClaims\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\"\x8b\x01\n" +
	"\x15ValidateTokenResponse\x127\n" +
	"\x06claims\x18\x01 \x01(\v2\x1d.kleff.plugins.v1.TokenClaimsH\x00R\x06claims\x12/\n" +
	"\x05error\x18\x02 \x01(\v2\x17.kleff.plugins.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"\x16\n" +
	"\x14GetOIDCConfigRequest\"\x8c\x03\n" +
	"\n" +
	"OIDCConfig\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x19\n" +
	"\bjwks_uri\x18\x03 \x01(\tR\ajwksUri\x12\x16\n" +
	"\x06scopes\x18\x04 \x03(\tR\x06scopes\x12\x1b\n" +
	"\tauth_mode\x18\x05 \x01(\tR\bauthMode\x12%\n" +
	"\x0etoken_endpoint\x18\x06 \x01(\tR\rtokenEndpoint\x125\n" +
	"\x16authorization_endpoint\x18\a \x01(\tR\x15authorizationEndpoint\x12+\n" +
	"\x11userinfo_endpoint\x18\b \x01(\tR\x10userinfoEndpoint\x120\n" +
	"\x14end_session_endpoint\x18\t \x01(\tR\x12endSessionEndpoint\x126\n" +
	"\x17internal_token_endpoint\x18\n" +
	" \x01(\tR\x15internalTokenEndpoint\"\x8a\x01\n" +
	"\x15GetOIDCConfigResponse\x126\n" +
	"\x06config\x18\x01 \x01(\v2\x1c.kleff.plugins.v1.OIDCConfigH\x00R\x06config\x12/\n" +
	"\x05error\x18\x02 \x01(\v2\x17.kleff.plugins.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"\x85\x01\n" +
	"\x14RefreshTokenResponse\x122\n" +
	"\x05token\x18\x01 \x01(\v2\x1a.kleff.plugins.v1.TokenSetH\x00R\x05token\x12/\n" +
	"\x05error\x18\x02 \x01(\v2\x17.kleff.plugins.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"~\n" +
	"\rLoginResponse\x122\n" +
	"\x05token\x18\x01 \x01(\v2\x1a.kleff.plugins.v1.TokenSetH\x00R\x05token\x12/\n" +
	"\x05error\x18\x02 \x01(\v2\x17.kleff.plugins.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"\xc1\x01\n" +
	"\bTokenSet\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x19\n" +
	"\bid_token\x18\x03 \x01(\tR\aidToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x04 \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x05 \x01(\x03R\texpiresIn\x12\x14\n" +
	"\x05scope\x18\x06 \x01(\tR\x05scope\"\x9b\x01\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\"h\n" +
	"\x10RegisterResponse\x12\x19\n" +
	"\auser_id\x18\x01 \x01(\tH\x00R\x06userId\x12/\n" +
	"\x05error\x18\x02 \x01(\v2\x17.kleff.plugins.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"~\n" +
	"\x0fGetUserResponse\x120\n" +
	"\x04user\x18\x01 \x01(\v2\x1a.kleff.plugins.v1.UserInfoH\x00R\x04user\x12/\n" +
	"\x05error\x18\x02 \x01(\v2\x17.kleff.plugins.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"\x91\x01\n" +
	"\bUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName2\xef\x04\n" +
	"\x10IdentityProvider\x12H\n" +
	"\x05Login\x12\x1e.kleff.plugins.v1.LoginRequest\x1a\x1f.kleff.plugins.v1.LoginResponse\x12Q\n" +
	"\bRegister\x12!.kleff.plugins.v1.RegisterRequest\x1a\".kleff.plugins.v1.RegisterResponse\x12N\n" +
	"\aGetUser\x12 .kleff.plugins.v1.GetUserRequest\x1a!.kleff.plugins.v1.GetUserResponse\x12`\n" +
	"\rValidateToken\x12&.kleff.plugins.v1.ValidateTokenRequest\x1a'.kleff.plugins.v1.ValidateTokenResponse\x12`\n" +
	"\rGetOIDCConfig\x12&.kleff.plugins.v1.GetOIDCConfigRequest\x1a'.kleff.plugins.v1.GetOIDCConfigResponse\x12]\n" +
	"\fRefreshToken\x12%.kleff.plugins.v1.RefreshTokenRequest\x1a&.kleff.plugins.v1.RefreshTokenResponse\x12K\n" +
	"\x06Health\x12\x1f.kleff.plugins.v1.HealthRequest\x1a .kleff.plugins.v1.HealthResponseB/Z-github.com/kleffio/plugin-sdk-go/v1;pluginsv1b\x06proto3"

var (
	file_identity_provider_proto_rawDescOnce sync.Once
	file_identity_provider_proto_rawDescData []byte
)

func file_identity_provider_proto_rawDescGZIP() []byte {
	file_identity_provider_proto_rawDescOnce.Do(func() {
		file_identity_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_provider_proto_rawDesc), len(file_identity_provider_proto_rawDesc)))
	})
	return file_identity_provider_proto_rawDescData
}

var file_identity_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_identity_provider_proto_goTypes = []any{
	(*ValidateTokenRequest)(nil),  // 0: kleff.plugins.v1.ValidateTokenRequest
	(*TokenClaims)(nil),           // 1: kleff.plugins.v1.TokenClaims
	(*ValidateTokenResponse)(nil), // 2: kleff.plugins.v1.ValidateTokenResponse
	(*GetOIDCConfigRequest)(nil),  // 3: kleff.plugins.v1.GetOIDCConfigRequest
	(*OIDCConfig)(nil),            // 4: kleff.plugins.v1.OIDCConfig
	(*GetOIDCConfigResponse)(nil), // 5: kleff.plugins.v1.GetOIDCConfigResponse
	(*RefreshTokenRequest)(nil),   // 6: kleff.plugins.v1.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),  // 7: kleff.plugins.v1.RefreshTokenResponse
	(*LoginRequest)(nil),          // 8: kleff.plugins.v1.LoginRequest
	(*LoginResponse)(nil),         // 9: kleff.plugins.v1.LoginResponse
	(*TokenSet)(nil),              // 10: kleff.plugins.v1.TokenSet
	(*RegisterRequest)(nil),       // 11: kleff.plugins.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 12: kleff.plugins.v1.RegisterResponse
	(*GetUserRequest)(nil),        // 13: kleff.plugins.v1.GetUserRequest
	(*GetUserResponse)(nil),       // 14: kleff.plugins.v1.GetUserResponse
	(*UserInfo)(nil),              // 15: kleff.plugins.v1.UserInfo
	(*Error)(nil),                 // 16: kleff.plugins.v1.Error
	(*HealthRequest)(nil),         // 17: kleff.plugins.v1.HealthRequest
	(*HealthResponse)(nil),        // 18: kleff.plugins.v1.HealthResponse
}
var file_identity_provider_proto_depIdxs = []int32{
	1,  // 0: kleff.plugins.v1.ValidateTokenResponse.claims:type_name -> kleff.plugins.v1.TokenClaims
	16, // 1: kleff.plugins.v1.ValidateTokenResponse.error:type_name -> kleff.plugins.v1.Error
	4,  // 2: kleff.plugins.v1.GetOIDCConfigResponse.config:type_name -> kleff.plugins.v1.OIDCConfig
	16, // 3: kleff.plugins.v1.GetOIDCConfigResponse.error:type_name -> kleff.plugins.v1.Error
	10, // 4: kleff.plugins.v1.RefreshTokenResponse.token:type_name -> kleff.plugins.v1.TokenSet
	16, // 5: kleff.plugins.v1.RefreshTokenResponse.error:type_name -> kleff.plugins.v1.Error
	10, // 6: kleff.plugins.v1.LoginResponse.token:type_name -> kleff.plugins.v1.TokenSet
	16, // 7: kleff.plugins.v1.LoginResponse.error:type_name -> kleff.plugins.v1.Error
	16, // 8: kleff.plugins.v1.RegisterResponse.error:type_name -> kleff.plugins.v1.Error
	15, // 9: kleff.plugins.v1.GetUserResponse.user:type_name -> kleff.plugins.v1.UserInfo
	16, // 10: kleff.plugins.v1.GetUserResponse.error:type_name -> kleff.plugins.v1.Error
	8,  // 11: kleff.plugins.v1.IdentityProvider.Login:input_type -> kleff.plugins.v1.LoginRequest
	11, // 12: kleff.plugins.v1.IdentityProvider.Register:input_type -> kleff.plugins.v1.RegisterRequest
	13, // 13: kleff.plugins.v1.IdentityProvider.GetUser:input_type -> kleff.plugins.v1.GetUserRequest
	0,  // 14: kleff.plugins.v1.IdentityProvider.ValidateToken:input_type -> kleff.plugins.v1.ValidateTokenRequest
	3,  // 15: kleff.plugins.v1.IdentityProvider.GetOIDCConfig:input_type -> kleff.plugins.v1.GetOIDCConfigRequest
	6,  // 16: kleff.plugins.v1.IdentityProvider.RefreshToken:input_type -> kleff.plugins.v1.RefreshTokenRequest
	17, // 17: kleff.plugins.v1.IdentityProvider.Health:input_type -> kleff.plugins.v1.HealthRequest
	9,  // 18: kleff.plugins.v1.IdentityProvider.Login:output_type -> kleff.plugins.v1.LoginResponse
	12, // 19: kleff.plugins.v1.IdentityProvider.Register:output_type -> kleff.plugins.v1.RegisterResponse
	14, // 20: kleff.plugins.v1.IdentityProvider.GetUser:output_type -> kleff.plugins.v1.GetUserResponse
	2,  // 21: kleff.plugins.v1.IdentityProvider.ValidateToken:output_type -> kleff.plugins.v1.ValidateTokenResponse
	5,  // 22: kleff.plugins.v1.IdentityProvider.GetOIDCConfig:output_type -> kleff.plugins.v1.GetOIDCConfigResponse
	7,  // 23: kleff.plugins.v1.IdentityProvider.RefreshToken:output_type -> kleff.plugins.v1.RefreshTokenResponse
	18, // 24: kleff.plugins.v1.IdentityProvider.Health:output_type -> kleff.plugins.v1.HealthResponse
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_identity_provider_proto_init() }
func file_identity_provider_proto_init() {
	if File_identity_provider_proto != nil {
		return
	}
	file_common_proto_init()
	file_identity_provider_proto_msgTypes[2].OneofWrappers = []any{
		(*ValidateTokenResponse_Claims)(nil),
		(*ValidateTokenResponse_Error)(nil),
	}
	file_identity_provider_proto_msgTypes[5].OneofWrappers = []any{
		(*GetOIDCConfigResponse_Config)(nil),
		(*GetOIDCConfigResponse_Error)(nil),
	}
	file_identity_provider_proto_msgTypes[7].OneofWrappers = []any{
		(*RefreshTokenResponse_Token)(nil),
		(*RefreshTokenResponse_Error)(nil),
	}
	file_identity_provider_proto_msgTypes[9].OneofWrappers = []any{
		(*LoginResponse_Token)(nil),
		(*LoginResponse_Error)(nil),
	}
	file_identity_provider_proto_msgTypes[12].OneofWrappers = []any{
		(*RegisterResponse_UserId)(nil),
		(*RegisterResponse_Error)(nil),
	}
	file_identity_provider_proto_msgTypes[14].OneofWrappers = []any{
		(*GetUserResponse_User)(nil),
		(*GetUserResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_provider_proto_rawDesc), len(file_identity_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_identity_provider_proto_goTypes,
		DependencyIndexes: file_identity_provider_proto_depIdxs,
		MessageInfos:      file_identity_provider_proto_msgTypes,
	}.Build()
	File_identity_provider_proto = out.File
	file_identity_provider_proto_goTypes = nil
	file_identity_provider_proto_depIdxs = nil
}
