// ui/manifest.proto
//
// UIManifest — plugins that contribute frontend components and navigation.
// Capability key: "ui.manifest"

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ui/manifest.proto

package pluginsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUIManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUIManifestRequest) Reset() {
	*x = GetUIManifestRequest{}
	mi := &file_ui_manifest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUIManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUIManifestRequest) ProtoMessage() {}

func (x *GetUIManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ui_manifest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUIManifestRequest.ProtoReflect.Descriptor instead.
func (*GetUIManifestRequest) Descriptor() ([]byte, []int) {
	return file_ui_manifest_proto_rawDescGZIP(), []int{0}
}

type GetUIManifestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetUIManifestResponse_Manifest
	//	*GetUIManifestResponse_Error
	Result        isGetUIManifestResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUIManifestResponse) Reset() {
	*x = GetUIManifestResponse{}
	mi := &file_ui_manifest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUIManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUIManifestResponse) ProtoMessage() {}

func (x *GetUIManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ui_manifest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUIManifestResponse.ProtoReflect.Descriptor instead.
func (*GetUIManifestResponse) Descriptor() ([]byte, []int) {
	return file_ui_manifest_proto_rawDescGZIP(), []int{1}
}

func (x *GetUIManifestResponse) GetResult() isGetUIManifestResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetUIManifestResponse) GetManifest() *UIManifest {
	if x != nil {
		if x, ok := x.Result.(*GetUIManifestResponse_Manifest); ok {
			return x.Manifest
		}
	}
	return nil
}

func (x *GetUIManifestResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*GetUIManifestResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGetUIManifestResponse_Result interface {
	isGetUIManifestResponse_Result()
}

type GetUIManifestResponse_Manifest struct {
	Manifest *UIManifest `protobuf:"bytes,1,opt,name=manifest,proto3,oneof"`
}

type GetUIManifestResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetUIManifestResponse_Manifest) isGetUIManifestResponse_Result() {}

func (*GetUIManifestResponse_Error) isGetUIManifestResponse_Result() {}

type UIManifest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NavItems        []*NavItem             `protobuf:"bytes,1,rep,name=nav_items,json=navItems,proto3" json:"nav_items,omitempty"`
	SettingsPages   []*SettingsPage        `protobuf:"bytes,2,rep,name=settings_pages,json=settingsPages,proto3" json:"settings_pages,omitempty"`
	ProfileSections []*ProfileSection      `protobuf:"bytes,3,rep,name=profile_sections,json=profileSections,proto3" json:"profile_sections,omitempty"`
	LoginConfig     *LoginConfig           `protobuf:"bytes,4,opt,name=login_config,json=loginConfig,proto3" json:"login_config,omitempty"`
	SignupConfig    *SignupConfig          `protobuf:"bytes,5,opt,name=signup_config,json=signupConfig,proto3" json:"signup_config,omitempty"`
	BundleUrl       string                 `protobuf:"bytes,6,opt,name=bundle_url,json=bundleUrl,proto3" json:"bundle_url,omitempty"` // JS module URL for dynamic loading
	PluginId        string                 `protobuf:"bytes,7,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`    // set by the platform after fetching
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UIManifest) Reset() {
	*x = UIManifest{}
	mi := &file_ui_manifest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIManifest) ProtoMessage() {}

func (x *UIManifest) ProtoReflect() protoreflect.Message {
	mi := &file_ui_manifest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIManifest.ProtoReflect.Descriptor instead.
func (*UIManifest) Descriptor() ([]byte, []int) {
	return file_ui_manifest_proto_rawDescGZIP(), []int{2}
}

func (x *UIManifest) GetNavItems() []*NavItem {
	if x != nil {
		return x.NavItems
	}
	return nil
}

func (x *UIManifest) GetSettingsPages() []*SettingsPage {
	if x != nil {
		return x.SettingsPages
	}
	return nil
}

func (x *UIManifest) GetProfileSections() []*ProfileSection {
	if x != nil {
		return x.ProfileSections
	}
	return nil
}

func (x *UIManifest) GetLoginConfig() *LoginConfig {
	if x != nil {
		return x.LoginConfig
	}
	return nil
}

func (x *UIManifest) GetSignupConfig() *SignupConfig {
	if x != nil {
		return x.SignupConfig
	}
	return nil
}

func (x *UIManifest) GetBundleUrl() string {
	if x != nil {
		return x.BundleUrl
	}
	return ""
}

func (x *UIManifest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

type NavItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Href          string                 `protobuf:"bytes,1,opt,name=href,proto3" json:"href,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NavItem) Reset() {
	*x = NavItem{}
	mi := &file_ui_manifest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavItem) ProtoMessage() {}

func (x *NavItem) ProtoReflect() protoreflect.Message {
	mi := &file_ui_manifest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavItem.ProtoReflect.Descriptor instead.
func (*NavItem) Descriptor() ([]byte, []int) {
	return file_ui_manifest_proto_rawDescGZIP(), []int{3}
}

func (x *NavItem) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

func (x *NavItem) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *NavItem) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

type SettingsPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Href          string                 `protobuf:"bytes,1,opt,name=href,proto3" json:"href,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Slot          string                 `protobuf:"bytes,3,opt,name=slot,proto3" json:"slot,omitempty"`                            // component slot ID in the bundle
	IframeUrl     string                 `protobuf:"bytes,4,opt,name=iframe_url,json=iframeUrl,proto3" json:"iframe_url,omitempty"` // if set, embed as iframe
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingsPage) Reset() {
	*x = SettingsPage{}
	mi := &file_ui_manifest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsPage) ProtoMessage() {}

func (x *SettingsPage) ProtoReflect() protoreflect.Message {
	mi := &file_ui_manifest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsPage.ProtoReflect.Descriptor instead.
func (*SettingsPage) Descriptor() ([]byte, []int) {
	return file_ui_manifest_proto_rawDescGZIP(), []int{4}
}

func (x *SettingsPage) GetHref() string {
	if x != nil {
		return x.Href
	}
	return ""
}

func (x *SettingsPage) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SettingsPage) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

func (x *SettingsPage) GetIframeUrl() string {
	if x != nil {
		return x.IframeUrl
	}
	return ""
}

type ProfileSection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Slot          string                 `protobuf:"bytes,2,opt,name=slot,proto3" json:"slot,omitempty"` // component slot ID in the bundle
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`     // unique identifier for this section
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	IframeUrl     string                 `protobuf:"bytes,5,opt,name=iframe_url,json=iframeUrl,proto3" json:"iframe_url,omitempty"` // if set, embed as iframe
	Actions       []string               `protobuf:"bytes,6,rep,name=actions,proto3" json:"actions,omitempty"`                      // native action keys (e.g. "change_password")
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfileSection) Reset() {
	*x = ProfileSection{}
	mi := &file_ui_manifest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileSection) ProtoMessage() {}

func (x *ProfileSection) ProtoReflect() protoreflect.Message {
	mi := &file_ui_manifest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileSection.ProtoReflect.Descriptor instead.
func (*ProfileSection) Descriptor() ([]byte, []int) {
	return file_ui_manifest_proto_rawDescGZIP(), []int{5}
}

func (x *ProfileSection) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ProfileSection) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

func (x *ProfileSection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProfileSection) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProfileSection) GetIframeUrl() string {
	if x != nil {
		return x.IframeUrl
	}
	return ""
}

func (x *ProfileSection) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

type LoginConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShowForm      bool                   `protobuf:"varint,1,opt,name=show_form,json=showForm,proto3" json:"show_form,omitempty"`         // render username/password form
	RedirectUrl   string                 `protobuf:"bytes,2,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"` // OIDC redirect if show_form = false
	ProviderName  string                 `protobuf:"bytes,3,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	ProviderLogo  string                 `protobuf:"bytes,4,opt,name=provider_logo,json=providerLogo,proto3" json:"provider_logo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginConfig) Reset() {
	*x = LoginConfig{}
	mi := &file_ui_manifest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginConfig) ProtoMessage() {}

func (x *LoginConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ui_manifest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginConfig.ProtoReflect.Descriptor instead.
func (*LoginConfig) Descriptor() ([]byte, []int) {
	return file_ui_manifest_proto_rawDescGZIP(), []int{6}
}

func (x *LoginConfig) GetShowForm() bool {
	if x != nil {
		return x.ShowForm
	}
	return false
}

func (x *LoginConfig) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

func (x *LoginConfig) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *LoginConfig) GetProviderLogo() string {
	if x != nil {
		return x.ProviderLogo
	}
	return ""
}

type SignupConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	RedirectUrl   string                 `protobuf:"bytes,2,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupConfig) Reset() {
	*x = SignupConfig{}
	mi := &file_ui_manifest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupConfig) ProtoMessage() {}

func (x *SignupConfig) ProtoReflect() protoreflect.Message {
	mi := &file_ui_manifest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupConfig.ProtoReflect.Descriptor instead.
func (*SignupConfig) Descriptor() ([]byte, []int) {
	return file_ui_manifest_proto_rawDescGZIP(), []int{7}
}

func (x *SignupConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SignupConfig) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

var File_ui_manifest_proto protoreflect.FileDescriptor

const file_ui_manifest_proto_rawDesc = "" +
	"\n" +
	"\x11ui/manifest.proto\x12\x10kleff.plugins.v1\x1a\fcommon.proto\"\x16\n" +
	"\x14GetUIManifestRequest\"\x8e\x01\n" +
	"\x15GetUIManifestResponse\x12:\n" +
	"\bmanifest\x18\x01 \x01(\v2\x1c.kleff.plugins.v1.UIManifestH\x00R\bmanifest\x12/\n" +
	"\x05error\x18\x02 \x01(\v2\x17.kleff.plugins.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\"\x9b\x03\n" +
	"\n" +
	"UIManifest\x126\n" +
	"\tnav_items\x18\x01 \x03(\v2\x19.kleff.plugins.v1.NavItemR\bnavItems\x12E\n" +
	"\x0esettings_pages\x18\x02 \x03(\v2\x1e.kleff.plugins.v1.SettingsPageR\rsettingsPages\x12K\n" +
	"\x10profile_sections\x18\x03 \x03(\v2 .kleff.plugins.v1.ProfileSectionR\x0fprofileSections\x12@\n" +
	"\flogin_config\x18\x04 \x01(\v2\x1d.kleff.plugins.v1.LoginConfigR\vloginConfig\x12C\n" +
	"\rsignup_config\x18\x05 \x01(\v2\x1e.kleff.plugins.v1.SignupConfigR\fsignupConfig\x12\x1d\n" +
	"\n" +
	"bundle_url\x18\x06 \x01(\tR\tbundleUrl\x12\x1b\n" +
	"\tplugin_id\x18\a \x01(\tR\bpluginId\"G\n" +
	"\aNavItem\x12\x12\n" +
	"\x04href\x18\x01 \x01(\tR\x04href\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\"k\n" +
	"\fSettingsPage\x12\x12\n" +
	"\x04href\x18\x01 \x01(\tR\x04href\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04slot\x18\x03 \x01(\tR\x04slot\x12\x1d\n" +
	"\n" +
	"iframe_url\x18\x04 \x01(\tR\tiframeUrl\"\xa5\x01\n" +
	"\x0eProfileSection\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\tR\x04slot\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"iframe_url\x18\x05 \x01(\tR\tiframeUrl\x12\x18\n" +
	"\aactions\x18\x06 \x03(\tR\aactions\"\x97\x01\n" +
	"\vLoginConfig\x12\x1b\n" +
	"\tshow_form\x18\x01 \x01(\bR\bshowForm\x12!\n" +
	"\fredirect_url\x18\x02 \x01(\tR\vredirectUrl\x12#\n" +
	"\rprovider_name\x18\x03 \x01(\tR\fproviderName\x12#\n" +
	"\rprovider_logo\x18\x04 \x01(\tR\fproviderLogo\"K\n" +
	"\fSignupConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12!\n" +
	"\fredirect_url\x18\x02 \x01(\tR\vredirectUrl2u\n" +
	"\x11UIManifestService\x12`\n" +
	"\rGetUIManifest\x12&.kleff.plugins.v1.GetUIManifestRequest\x1a'.kleff.plugins.v1.GetUIManifestResponseB/Z-github.com/kleffio/plugin-sdk-go/v1;pluginsv1b\x06proto3"

var (
	file_ui_manifest_proto_rawDescOnce sync.Once
	file_ui_manifest_proto_rawDescData []byte
)

func file_ui_manifest_proto_rawDescGZIP() []byte {
	file_ui_manifest_proto_rawDescOnce.Do(func() {
		file_ui_manifest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ui_manifest_proto_rawDesc), len(file_ui_manifest_proto_rawDesc)))
	})
	return file_ui_manifest_proto_rawDescData
}

var file_ui_manifest_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_ui_manifest_proto_goTypes = []any{
	(*GetUIManifestRequest)(nil),  // 0: kleff.plugins.v1.GetUIManifestRequest
	(*GetUIManifestResponse)(nil), // 1: kleff.plugins.v1.GetUIManifestResponse
	(*UIManifest)(nil),            // 2: kleff.plugins.v1.UIManifest
	(*NavItem)(nil),               // 3: kleff.plugins.v1.NavItem
	(*SettingsPage)(nil),          // 4: kleff.plugins.v1.SettingsPage
	(*ProfileSection)(nil),        // 5: kleff.plugins.v1.ProfileSection
	(*LoginConfig)(nil),           // 6: kleff.plugins.v1.LoginConfig
	(*SignupConfig)(nil),          // 7: kleff.plugins.v1.SignupConfig
	(*Error)(nil),                 // 8: kleff.plugins.v1.Error
}
var file_ui_manifest_proto_depIdxs = []int32{
	2, // 0: kleff.plugins.v1.GetUIManifestResponse.manifest:type_name -> kleff.plugins.v1.UIManifest
	8, // 1: kleff.plugins.v1.GetUIManifestResponse.error:type_name -> kleff.plugins.v1.Error
	3, // 2: kleff.plugins.v1.UIManifest.nav_items:type_name -> kleff.plugins.v1.NavItem
	4, // 3: kleff.plugins.v1.UIManifest.settings_pages:type_name -> kleff.plugins.v1.SettingsPage
	5, // 4: kleff.plugins.v1.UIManifest.profile_sections:type_name -> kleff.plugins.v1.ProfileSection
	6, // 5: kleff.plugins.v1.UIManifest.login_config:type_name -> kleff.plugins.v1.LoginConfig
	7, // 6: kleff.plugins.v1.UIManifest.signup_config:type_name -> kleff.plugins.v1.SignupConfig
	0, // 7: kleff.plugins.v1.UIManifestService.GetUIManifest:input_type -> kleff.plugins.v1.GetUIManifestRequest
	1, // 8: kleff.plugins.v1.UIManifestService.GetUIManifest:output_type -> kleff.plugins.v1.GetUIManifestResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_ui_manifest_proto_init() }
func file_ui_manifest_proto_init() {
	if File_ui_manifest_proto != nil {
		return
	}
	file_common_proto_init()
	file_ui_manifest_proto_msgTypes[1].OneofWrappers = []any{
		(*GetUIManifestResponse_Manifest)(nil),
		(*GetUIManifestResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ui_manifest_proto_rawDesc), len(file_ui_manifest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ui_manifest_proto_goTypes,
		DependencyIndexes: file_ui_manifest_proto_depIdxs,
		MessageInfos:      file_ui_manifest_proto_msgTypes,
	}.Build()
	File_ui_manifest_proto = out.File
	file_ui_manifest_proto_goTypes = nil
	file_ui_manifest_proto_depIdxs = nil
}
