// ui/manifest.proto
//
// UIManifest — plugins that contribute frontend components and navigation.
// Capability key: "ui.manifest"

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: ui/manifest.proto

package pluginsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UIManifestService_GetUIManifest_FullMethodName = "/kleff.plugins.v1.UIManifestService/GetUIManifest"
)

// UIManifestServiceClient is the client API for UIManifestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UIManifestServiceClient interface {
	GetUIManifest(ctx context.Context, in *GetUIManifestRequest, opts ...grpc.CallOption) (*GetUIManifestResponse, error)
}

type uIManifestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUIManifestServiceClient(cc grpc.ClientConnInterface) UIManifestServiceClient {
	return &uIManifestServiceClient{cc}
}

func (c *uIManifestServiceClient) GetUIManifest(ctx context.Context, in *GetUIManifestRequest, opts ...grpc.CallOption) (*GetUIManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUIManifestResponse)
	err := c.cc.Invoke(ctx, UIManifestService_GetUIManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UIManifestServiceServer is the server API for UIManifestService service.
// All implementations must embed UnimplementedUIManifestServiceServer
// for forward compatibility.
type UIManifestServiceServer interface {
	GetUIManifest(context.Context, *GetUIManifestRequest) (*GetUIManifestResponse, error)
	mustEmbedUnimplementedUIManifestServiceServer()
}

// UnimplementedUIManifestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUIManifestServiceServer struct{}

func (UnimplementedUIManifestServiceServer) GetUIManifest(context.Context, *GetUIManifestRequest) (*GetUIManifestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUIManifest not implemented")
}
func (UnimplementedUIManifestServiceServer) mustEmbedUnimplementedUIManifestServiceServer() {}
func (UnimplementedUIManifestServiceServer) testEmbeddedByValue()                           {}

// UnsafeUIManifestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UIManifestServiceServer will
// result in compilation errors.
type UnsafeUIManifestServiceServer interface {
	mustEmbedUnimplementedUIManifestServiceServer()
}

func RegisterUIManifestServiceServer(s grpc.ServiceRegistrar, srv UIManifestServiceServer) {
	// If the following call panics, it indicates UnimplementedUIManifestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UIManifestService_ServiceDesc, srv)
}

func _UIManifestService_GetUIManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUIManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UIManifestServiceServer).GetUIManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UIManifestService_GetUIManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UIManifestServiceServer).GetUIManifest(ctx, req.(*GetUIManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UIManifestService_ServiceDesc is the grpc.ServiceDesc for UIManifestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UIManifestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kleff.plugins.v1.UIManifestService",
	HandlerType: (*UIManifestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUIManifest",
			Handler:    _UIManifestService_GetUIManifest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ui/manifest.proto",
}
