// api/middleware.proto
//
// APIMiddleware — plugins that intercept every authenticated HTTP request.
// Called before the handler; can reject, modify headers, or enrich context.
// Capability key: "api.middleware"

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: api/middleware.proto

package pluginsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	APIMiddleware_OnRequest_FullMethodName = "/kleff.plugins.v1.APIMiddleware/OnRequest"
)

// APIMiddlewareClient is the client API for APIMiddleware service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type APIMiddlewareClient interface {
	OnRequest(ctx context.Context, in *MiddlewareRequest, opts ...grpc.CallOption) (*MiddlewareResponse, error)
}

type aPIMiddlewareClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIMiddlewareClient(cc grpc.ClientConnInterface) APIMiddlewareClient {
	return &aPIMiddlewareClient{cc}
}

func (c *aPIMiddlewareClient) OnRequest(ctx context.Context, in *MiddlewareRequest, opts ...grpc.CallOption) (*MiddlewareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MiddlewareResponse)
	err := c.cc.Invoke(ctx, APIMiddleware_OnRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIMiddlewareServer is the server API for APIMiddleware service.
// All implementations must embed UnimplementedAPIMiddlewareServer
// for forward compatibility.
type APIMiddlewareServer interface {
	OnRequest(context.Context, *MiddlewareRequest) (*MiddlewareResponse, error)
	mustEmbedUnimplementedAPIMiddlewareServer()
}

// UnimplementedAPIMiddlewareServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAPIMiddlewareServer struct{}

func (UnimplementedAPIMiddlewareServer) OnRequest(context.Context, *MiddlewareRequest) (*MiddlewareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OnRequest not implemented")
}
func (UnimplementedAPIMiddlewareServer) mustEmbedUnimplementedAPIMiddlewareServer() {}
func (UnimplementedAPIMiddlewareServer) testEmbeddedByValue()                       {}

// UnsafeAPIMiddlewareServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to APIMiddlewareServer will
// result in compilation errors.
type UnsafeAPIMiddlewareServer interface {
	mustEmbedUnimplementedAPIMiddlewareServer()
}

func RegisterAPIMiddlewareServer(s grpc.ServiceRegistrar, srv APIMiddlewareServer) {
	// If the following call panics, it indicates UnimplementedAPIMiddlewareServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&APIMiddleware_ServiceDesc, srv)
}

func _APIMiddleware_OnRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MiddlewareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIMiddlewareServer).OnRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIMiddleware_OnRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIMiddlewareServer).OnRequest(ctx, req.(*MiddlewareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// APIMiddleware_ServiceDesc is the grpc.ServiceDesc for APIMiddleware service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var APIMiddleware_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kleff.plugins.v1.APIMiddleware",
	HandlerType: (*APIMiddlewareServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnRequest",
			Handler:    _APIMiddleware_OnRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/middleware.proto",
}
