// api/middleware.proto
//
// APIMiddleware — plugins that intercept every authenticated HTTP request.
// Called before the handler; can reject, modify headers, or enrich context.
// Capability key: "api.middleware"

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/middleware.proto

package pluginsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MiddlewareRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Roles         []string               `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiddlewareRequest) Reset() {
	*x = MiddlewareRequest{}
	mi := &file_api_middleware_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiddlewareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiddlewareRequest) ProtoMessage() {}

func (x *MiddlewareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_middleware_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiddlewareRequest.ProtoReflect.Descriptor instead.
func (*MiddlewareRequest) Descriptor() ([]byte, []int) {
	return file_api_middleware_proto_rawDescGZIP(), []int{0}
}

func (x *MiddlewareRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MiddlewareRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *MiddlewareRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *MiddlewareRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MiddlewareRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type MiddlewareResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allow         bool                   `protobuf:"varint,1,opt,name=allow,proto3" json:"allow,omitempty"`
	AddHeaders    map[string]string      `protobuf:"bytes,2,rep,name=add_headers,json=addHeaders,proto3" json:"add_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // injected into the upstream request
	DenyReason    string                 `protobuf:"bytes,3,opt,name=deny_reason,json=denyReason,proto3" json:"deny_reason,omitempty"`                                                                           // shown to caller if allow = false
	DenyStatus    int32                  `protobuf:"varint,4,opt,name=deny_status,json=denyStatus,proto3" json:"deny_status,omitempty"`                                                                          // HTTP status if allow = false (default 403)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiddlewareResponse) Reset() {
	*x = MiddlewareResponse{}
	mi := &file_api_middleware_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiddlewareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiddlewareResponse) ProtoMessage() {}

func (x *MiddlewareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_middleware_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiddlewareResponse.ProtoReflect.Descriptor instead.
func (*MiddlewareResponse) Descriptor() ([]byte, []int) {
	return file_api_middleware_proto_rawDescGZIP(), []int{1}
}

func (x *MiddlewareResponse) GetAllow() bool {
	if x != nil {
		return x.Allow
	}
	return false
}

func (x *MiddlewareResponse) GetAddHeaders() map[string]string {
	if x != nil {
		return x.AddHeaders
	}
	return nil
}

func (x *MiddlewareResponse) GetDenyReason() string {
	if x != nil {
		return x.DenyReason
	}
	return ""
}

func (x *MiddlewareResponse) GetDenyStatus() int32 {
	if x != nil {
		return x.DenyStatus
	}
	return 0
}

var File_api_middleware_proto protoreflect.FileDescriptor

const file_api_middleware_proto_rawDesc = "" +
	"\n" +
	"\x14api/middleware.proto\x12\x10kleff.plugins.v1\x1a\fcommon.proto\"\xf6\x01\n" +
	"\x11MiddlewareRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12J\n" +
	"\aheaders\x18\x05 \x03(\v20.kleff.plugins.v1.MiddlewareRequest.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x02\n" +
	"\x12MiddlewareResponse\x12\x14\n" +
	"\x05allow\x18\x01 \x01(\bR\x05allow\x12U\n" +
	"\vadd_headers\x18\x02 \x03(\v24.kleff.plugins.v1.MiddlewareResponse.AddHeadersEntryR\n" +
	"addHeaders\x12\x1f\n" +
	"\vdeny_reason\x18\x03 \x01(\tR\n" +
	"denyReason\x12\x1f\n" +
	"\vdeny_status\x18\x04 \x01(\x05R\n" +
	"denyStatus\x1a=\n" +
	"\x0fAddHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012g\n" +
	"\rAPIMiddleware\x12V\n" +
	"\tOnRequest\x12#.kleff.plugins.v1.MiddlewareRequest\x1a$.kleff.plugins.v1.MiddlewareResponseB/Z-github.com/kleffio/plugin-sdk-go/v1;pluginsv1b\x06proto3"

var (
	file_api_middleware_proto_rawDescOnce sync.Once
	file_api_middleware_proto_rawDescData []byte
)

func file_api_middleware_proto_rawDescGZIP() []byte {
	file_api_middleware_proto_rawDescOnce.Do(func() {
		file_api_middleware_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_middleware_proto_rawDesc), len(file_api_middleware_proto_rawDesc)))
	})
	return file_api_middleware_proto_rawDescData
}

var file_api_middleware_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_middleware_proto_goTypes = []any{
	(*MiddlewareRequest)(nil),  // 0: kleff.plugins.v1.MiddlewareRequest
	(*MiddlewareResponse)(nil), // 1: kleff.plugins.v1.MiddlewareResponse
	nil,                        // 2: kleff.plugins.v1.MiddlewareRequest.HeadersEntry
	nil,                        // 3: kleff.plugins.v1.MiddlewareResponse.AddHeadersEntry
}
var file_api_middleware_proto_depIdxs = []int32{
	2, // 0: kleff.plugins.v1.MiddlewareRequest.headers:type_name -> kleff.plugins.v1.MiddlewareRequest.HeadersEntry
	3, // 1: kleff.plugins.v1.MiddlewareResponse.add_headers:type_name -> kleff.plugins.v1.MiddlewareResponse.AddHeadersEntry
	0, // 2: kleff.plugins.v1.APIMiddleware.OnRequest:input_type -> kleff.plugins.v1.MiddlewareRequest
	1, // 3: kleff.plugins.v1.APIMiddleware.OnRequest:output_type -> kleff.plugins.v1.MiddlewareResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_middleware_proto_init() }
func file_api_middleware_proto_init() {
	if File_api_middleware_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_middleware_proto_rawDesc), len(file_api_middleware_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_middleware_proto_goTypes,
		DependencyIndexes: file_api_middleware_proto_depIdxs,
		MessageInfos:      file_api_middleware_proto_msgTypes,
	}.Build()
	File_api_middleware_proto = out.File
	file_api_middleware_proto_goTypes = nil
	file_api_middleware_proto_depIdxs = nil
}
