// api/routes.proto
//
// APIRoutes — plugins that own HTTP route namespaces under /api/v1/p/{plugin}.
// Capability key: "api.routes"

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/routes.proto

package pluginsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoutesRequest) Reset() {
	*x = GetRoutesRequest{}
	mi := &file_api_routes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoutesRequest) ProtoMessage() {}

func (x *GetRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_routes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoutesRequest.ProtoReflect.Descriptor instead.
func (*GetRoutesRequest) Descriptor() ([]byte, []int) {
	return file_api_routes_proto_rawDescGZIP(), []int{0}
}

type GetRoutesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetRoutesResponse_Routes
	//	*GetRoutesResponse_Error
	Result        isGetRoutesResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoutesResponse) Reset() {
	*x = GetRoutesResponse{}
	mi := &file_api_routes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoutesResponse) ProtoMessage() {}

func (x *GetRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_routes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoutesResponse.ProtoReflect.Descriptor instead.
func (*GetRoutesResponse) Descriptor() ([]byte, []int) {
	return file_api_routes_proto_rawDescGZIP(), []int{1}
}

func (x *GetRoutesResponse) GetResult() isGetRoutesResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetRoutesResponse) GetRoutes() *RouteList {
	if x != nil {
		if x, ok := x.Result.(*GetRoutesResponse_Routes); ok {
			return x.Routes
		}
	}
	return nil
}

func (x *GetRoutesResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*GetRoutesResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGetRoutesResponse_Result interface {
	isGetRoutesResponse_Result()
}

type GetRoutesResponse_Routes struct {
	Routes *RouteList `protobuf:"bytes,1,opt,name=routes,proto3,oneof"`
}

type GetRoutesResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetRoutesResponse_Routes) isGetRoutesResponse_Result() {}

func (*GetRoutesResponse_Error) isGetRoutesResponse_Result() {}

type RouteList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Route               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteList) Reset() {
	*x = RouteList{}
	mi := &file_api_routes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteList) ProtoMessage() {}

func (x *RouteList) ProtoReflect() protoreflect.Message {
	mi := &file_api_routes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteList.ProtoReflect.Descriptor instead.
func (*RouteList) Descriptor() ([]byte, []int) {
	return file_api_routes_proto_rawDescGZIP(), []int{2}
}

func (x *RouteList) GetItems() []*Route {
	if x != nil {
		return x.Items
	}
	return nil
}

type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`   // "GET", "POST", etc. — "*" for any
	Pattern       string                 `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"` // e.g. "/users/{id}"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_api_routes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_api_routes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_api_routes_proto_rawDescGZIP(), []int{3}
}

func (x *Route) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Route) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

type HandleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	PathParams    map[string]string      `protobuf:"bytes,5,rep,name=path_params,json=pathParams,proto3" json:"path_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UserId        string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Roles         []string               `protobuf:"bytes,7,rep,name=roles,proto3" json:"roles,omitempty"`
	RawQuery      string                 `protobuf:"bytes,8,opt,name=raw_query,json=rawQuery,proto3" json:"raw_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleRequest) Reset() {
	*x = HandleRequest{}
	mi := &file_api_routes_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleRequest) ProtoMessage() {}

func (x *HandleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_routes_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleRequest.ProtoReflect.Descriptor instead.
func (*HandleRequest) Descriptor() ([]byte, []int) {
	return file_api_routes_proto_rawDescGZIP(), []int{4}
}

func (x *HandleRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HandleRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HandleRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HandleRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HandleRequest) GetPathParams() map[string]string {
	if x != nil {
		return x.PathParams
	}
	return nil
}

func (x *HandleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *HandleRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *HandleRequest) GetRawQuery() string {
	if x != nil {
		return x.RawQuery
	}
	return ""
}

type HandleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleResponse) Reset() {
	*x = HandleResponse{}
	mi := &file_api_routes_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleResponse) ProtoMessage() {}

func (x *HandleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_routes_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleResponse.ProtoReflect.Descriptor instead.
func (*HandleResponse) Descriptor() ([]byte, []int) {
	return file_api_routes_proto_rawDescGZIP(), []int{5}
}

func (x *HandleResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HandleResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HandleResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_api_routes_proto protoreflect.FileDescriptor

const file_api_routes_proto_rawDesc = "" +
	"\n" +
	"\x10api/routes.proto\x12\x10kleff.plugins.v1\x1a\fcommon.proto\"\x12\n" +
	"\x10GetRoutesRequest\"\x85\x01\n" +
	"\x11GetRoutesResponse\x125\n" +
	"\x06routes\x18\x01 \x01(\v2\x1b.kleff.plugins.v1.RouteListH\x00R\x06routes\x12/\n" +
	"\x05error\x18\x02 \x01(\v2\x17.kleff.plugins.v1.ErrorH\x00R\x05errorB\b\n" +
	"\x06result\":\n" +
	"\tRouteList\x12-\n" +
	"\x05items\x18\x01 \x03(\v2\x17.kleff.plugins.v1.RouteR\x05items\"9\n" +
	"\x05Route\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x18\n" +
	"\apattern\x18\x02 \x01(\tR\apattern\"\xb0\x03\n" +
	"\rHandleRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12F\n" +
	"\aheaders\x18\x03 \x03(\v2,.kleff.plugins.v1.HandleRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12P\n" +
	"\vpath_params\x18\x05 \x03(\v2/.kleff.plugins.v1.HandleRequest.PathParamsEntryR\n" +
	"pathParams\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\x12\x14\n" +
	"\x05roles\x18\a \x03(\tR\x05roles\x12\x1b\n" +
	"\traw_query\x18\b \x01(\tR\brawQuery\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fPathParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc1\x01\n" +
	"\x0eHandleResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12G\n" +
	"\aheaders\x18\x02 \x03(\v2-.kleff.plugins.v1.HandleResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xae\x01\n" +
	"\tAPIRoutes\x12T\n" +
	"\tGetRoutes\x12\".kleff.plugins.v1.GetRoutesRequest\x1a#.kleff.plugins.v1.GetRoutesResponse\x12K\n" +
	"\x06Handle\x12\x1f.kleff.plugins.v1.HandleRequest\x1a .kleff.plugins.v1.HandleResponseB/Z-github.com/kleffio/plugin-sdk-go/v1;pluginsv1b\x06proto3"

var (
	file_api_routes_proto_rawDescOnce sync.Once
	file_api_routes_proto_rawDescData []byte
)

func file_api_routes_proto_rawDescGZIP() []byte {
	file_api_routes_proto_rawDescOnce.Do(func() {
		file_api_routes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_routes_proto_rawDesc), len(file_api_routes_proto_rawDesc)))
	})
	return file_api_routes_proto_rawDescData
}

var file_api_routes_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_routes_proto_goTypes = []any{
	(*GetRoutesRequest)(nil),  // 0: kleff.plugins.v1.GetRoutesRequest
	(*GetRoutesResponse)(nil), // 1: kleff.plugins.v1.GetRoutesResponse
	(*RouteList)(nil),         // 2: kleff.plugins.v1.RouteList
	(*Route)(nil),             // 3: kleff.plugins.v1.Route
	(*HandleRequest)(nil),     // 4: kleff.plugins.v1.HandleRequest
	(*HandleResponse)(nil),    // 5: kleff.plugins.v1.HandleResponse
	nil,                       // 6: kleff.plugins.v1.HandleRequest.HeadersEntry
	nil,                       // 7: kleff.plugins.v1.HandleRequest.PathParamsEntry
	nil,                       // 8: kleff.plugins.v1.HandleResponse.HeadersEntry
	(*Error)(nil),             // 9: kleff.plugins.v1.Error
}
var file_api_routes_proto_depIdxs = []int32{
	2, // 0: kleff.plugins.v1.GetRoutesResponse.routes:type_name -> kleff.plugins.v1.RouteList
	9, // 1: kleff.plugins.v1.GetRoutesResponse.error:type_name -> kleff.plugins.v1.Error
	3, // 2: kleff.plugins.v1.RouteList.items:type_name -> kleff.plugins.v1.Route
	6, // 3: kleff.plugins.v1.HandleRequest.headers:type_name -> kleff.plugins.v1.HandleRequest.HeadersEntry
	7, // 4: kleff.plugins.v1.HandleRequest.path_params:type_name -> kleff.plugins.v1.HandleRequest.PathParamsEntry
	8, // 5: kleff.plugins.v1.HandleResponse.headers:type_name -> kleff.plugins.v1.HandleResponse.HeadersEntry
	0, // 6: kleff.plugins.v1.APIRoutes.GetRoutes:input_type -> kleff.plugins.v1.GetRoutesRequest
	4, // 7: kleff.plugins.v1.APIRoutes.Handle:input_type -> kleff.plugins.v1.HandleRequest
	1, // 8: kleff.plugins.v1.APIRoutes.GetRoutes:output_type -> kleff.plugins.v1.GetRoutesResponse
	5, // 9: kleff.plugins.v1.APIRoutes.Handle:output_type -> kleff.plugins.v1.HandleResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_routes_proto_init() }
func file_api_routes_proto_init() {
	if File_api_routes_proto != nil {
		return
	}
	file_common_proto_init()
	file_api_routes_proto_msgTypes[1].OneofWrappers = []any{
		(*GetRoutesResponse_Routes)(nil),
		(*GetRoutesResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_routes_proto_rawDesc), len(file_api_routes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_routes_proto_goTypes,
		DependencyIndexes: file_api_routes_proto_depIdxs,
		MessageInfos:      file_api_routes_proto_msgTypes,
	}.Build()
	File_api_routes_proto = out.File
	file_api_routes_proto_goTypes = nil
	file_api_routes_proto_depIdxs = nil
}
