// api/routes.proto
//
// APIRoutes — plugins that own HTTP route namespaces under /api/v1/p/{plugin}.
// Capability key: "api.routes"

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: api/routes.proto

package pluginsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	APIRoutes_GetRoutes_FullMethodName = "/kleff.plugins.v1.APIRoutes/GetRoutes"
	APIRoutes_Handle_FullMethodName    = "/kleff.plugins.v1.APIRoutes/Handle"
)

// APIRoutesClient is the client API for APIRoutes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type APIRoutesClient interface {
	// Called once at plugin registration to declare owned routes.
	GetRoutes(ctx context.Context, in *GetRoutesRequest, opts ...grpc.CallOption) (*GetRoutesResponse, error)
	// Called for every matched request.
	Handle(ctx context.Context, in *HandleRequest, opts ...grpc.CallOption) (*HandleResponse, error)
}

type aPIRoutesClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIRoutesClient(cc grpc.ClientConnInterface) APIRoutesClient {
	return &aPIRoutesClient{cc}
}

func (c *aPIRoutesClient) GetRoutes(ctx context.Context, in *GetRoutesRequest, opts ...grpc.CallOption) (*GetRoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoutesResponse)
	err := c.cc.Invoke(ctx, APIRoutes_GetRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIRoutesClient) Handle(ctx context.Context, in *HandleRequest, opts ...grpc.CallOption) (*HandleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleResponse)
	err := c.cc.Invoke(ctx, APIRoutes_Handle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIRoutesServer is the server API for APIRoutes service.
// All implementations must embed UnimplementedAPIRoutesServer
// for forward compatibility.
type APIRoutesServer interface {
	// Called once at plugin registration to declare owned routes.
	GetRoutes(context.Context, *GetRoutesRequest) (*GetRoutesResponse, error)
	// Called for every matched request.
	Handle(context.Context, *HandleRequest) (*HandleResponse, error)
	mustEmbedUnimplementedAPIRoutesServer()
}

// UnimplementedAPIRoutesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAPIRoutesServer struct{}

func (UnimplementedAPIRoutesServer) GetRoutes(context.Context, *GetRoutesRequest) (*GetRoutesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoutes not implemented")
}
func (UnimplementedAPIRoutesServer) Handle(context.Context, *HandleRequest) (*HandleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Handle not implemented")
}
func (UnimplementedAPIRoutesServer) mustEmbedUnimplementedAPIRoutesServer() {}
func (UnimplementedAPIRoutesServer) testEmbeddedByValue()                   {}

// UnsafeAPIRoutesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to APIRoutesServer will
// result in compilation errors.
type UnsafeAPIRoutesServer interface {
	mustEmbedUnimplementedAPIRoutesServer()
}

func RegisterAPIRoutesServer(s grpc.ServiceRegistrar, srv APIRoutesServer) {
	// If the following call panics, it indicates UnimplementedAPIRoutesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&APIRoutes_ServiceDesc, srv)
}

func _APIRoutes_GetRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIRoutesServer).GetRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIRoutes_GetRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIRoutesServer).GetRoutes(ctx, req.(*GetRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIRoutes_Handle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIRoutesServer).Handle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIRoutes_Handle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIRoutesServer).Handle(ctx, req.(*HandleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// APIRoutes_ServiceDesc is the grpc.ServiceDesc for APIRoutes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var APIRoutes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kleff.plugins.v1.APIRoutes",
	HandlerType: (*APIRoutesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRoutes",
			Handler:    _APIRoutes_GetRoutes_Handler,
		},
		{
			MethodName: "Handle",
			Handler:    _APIRoutes_Handle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/routes.proto",
}
